### ISSUE TITLE
Spatial Type Support For Stored Procedure Parameters

### ISSUE THREAD

**Issue by feaselkl** [fsprojects/FSharp.Data.SqlClient#102]
Spatial types (HIERARCHYID, GEOMETRY, GEOGRAPHY) currently work in SQL result sets just fine, but when trying to use a stored procedure which defines a spatial type as a parameter, the resulting method is typed as a SqlHierarchyId rather than the appropriate spatial type.

Example using AdventureWorks2012:
```sql
CREATE PROCEDURE Person.Address_GetAddressBySpatialLocation
	@SpatialLocation GEOGRAPHY
AS
SELECT
	AddressLine1,
	City,
	SpatialLocation
FROM Person.[Address]
WHERE
	SpatialLocation.STDistance(@SpatialLocation) = 0;
GO
```

The problem is that spatial types are special:  all three have a system type ID of 240 but different user type IDs.  When GetParameters builds dataTypeMappings, `ps.USER_DEFINED_TYPE_NAME` is NULL for spatial types (because they are not user-defined table types) and the subsequent call to findBySqlEngineTypeIdAndUdtt returns the first type with system type ID = 240, which is HIERARCHYID.

**Comment by dmitry-a-morozov** [comment]
Hi, thank you for discovering the issue and submitting PR !
It's all merged. 
A new version 1.5.6 has been uploaded on Nuget.
