### ISSUE TITLE
Error using library in Mono

### ISSUE THREAD

**Issue by rojepp** [fsprojects/FSharp.Data.SqlClient#105]
Compiling a simple app on Mono yields 

> The type provider 'FSharp.Data.SqlCommandProvider' reported an error: Monitor thread failed while initializing. (FS3033) (skrapa)

The same app works on Windows/.Net.

**Comment by rojepp** [comment]
It would be great if the Travis build could connect to at least an azure database to see that this lib still works on mono. Is there an azure sql db somewhere that could be used?

**Comment by dmitry-a-morozov** [comment]
Yes, there is one
https://github.com/fsprojects/FSharp.Data.SqlClient/blob/master/src/SqlClient.Tests/ConnectionStrings.fs#L10
Better CI is on my "TO DO" list

**Comment by dmitry-a-morozov** [comment]
Any chance you can help me to find a root cause?

**Comment by rojepp** [comment]
Yes. Now that I've found out about .Raw, it is worth investing some time in
it. ;) Give me a few days.

**Comment by dmitry-a-morozov** [comment]
Be careful with ```.Raw`` - it's not officially supported :)

**Comment by rojepp** [comment]
The first failure (there may be more, not sure yet) is that `GetSchema("DataTypes")` doesn't return these types on mono:

> Microsoft.SqlServer.Types.SqlHierarchyId, Microsoft.SqlServer.Types, Version=11.
0.0.0, PublicKeyToken=89845dcd8080cc91 29 "Microsoft.SqlServer.Types.SqlHierarch
yId, Microsoft.SqlServer.Types, Version=11.0.0.0, PublicKeyToken=89845dcd8080cc9
1" Some false
> Microsoft.SqlServer.Types.SqlGeometry, Microsoft.SqlServer.Types, Version=11.0.0
.0, PublicKeyToken=89845dcd8080cc91 29 "Microsoft.SqlServer.Types.SqlGeometry, M
icrosoft.SqlServer.Types, Version=11.0.0.0, PublicKeyToken=89845dcd8080cc91" Som
e false
> Microsoft.SqlServer.Types.SqlGeography, Microsoft.SqlServer.Types, Version=11.0.
0.0, PublicKeyToken=89845dcd8080cc91 29 "Microsoft.SqlServer.Types.SqlGeography,
 Microsoft.SqlServer.Types, Version=11.0.0.0, PublicKeyToken=89845dcd8080cc91" S
ome false
[||]

This is just from a debug printout. An exception gets thrown [here](https://github.com/fsprojects/FSharp.Data.SqlClient/blob/master/src/SqlClient/SqlClientExtensions.fs#L363)

What to do? 
* Add these rows manually on mono
* Not throw an exception (I *think* these types aren't used that often)

**Comment by rojepp** [comment]
This problem will likely go away as mono and .net merge. 
This is what .net GetSchema executes to get all UDTs:
http://referencesource.microsoft.com/#System.Data/System/Data/SqlClient/sqlmetadatafactory.cs,45

**Comment by rojepp** [comment]
Good news is that if those missing types are ignored rather than throwing an exception, it works! (Given that you don't use those types, I suppose)
Part of a fix should be to actually exercise the TP in the OS-X build. :)

**Comment by rojepp** [comment]
Connecting to Azure SQL DB does not seem to be working in mono, so its hard to tests the provider from CI, unless we can find a regular public sql server to connect to?

http://stackoverflow.com/a/16379517/9436
