### ISSUE TITLE
FileSystemWatcher not working properly

### ISSUE THREAD

**Issue by rojepp** [fsprojects/FSharp.Data.SqlClient#110]
I was surprised to see changes to my sql file not being picked up:
```fsharp
  type Assessments  = SqlCommandProvider< "sql/Assessment.sql", cn>
```
So I looked in the code and found that the FileSystemWatcher would watch the source folder, with a filter of 'sql/Assessments.sql'. So I changed it to this and it worked:

```fsharp
  type Assessments  = SqlCommandProvider<"Assessment.sql", cn, ResolutionFolder = "sql">
```

Then, I couldn't load this .fs file from another folder, so I changed it to 
```fsharp
  [<Literal>] 
  let AssessmentFile = __SOURCE_DIRECTORY__ + "/sql/Assessment.sql"
  type Assessments  = SqlCommandProvider<AssessmentFile, cn>
```
and it compiles, but stops picking upp changes because the FSW code seems to fail when file is rooted. And this final scenario works, even when doing `#load` from another folder: 
```fsharp
  [<Literal>] 
  let sqlFolder = __SOURCE_DIRECTORY__ + "/sql/"
  type Assessments  = SqlCommandProvider<"Assessments.sql", cn, ResolutionFolder = sqlFolder>
```

Question: What is the purpose of ResolutionFolder? The TP will only ever read one file. 

These are the changes I'd like to see: 
 * Unless path is rooted, use the file directory as root, so no need for `__SOURCE_DIRECTORY__` to make it loadable from scripts in other folders.
 * Make the FileSystemWatcher work with rooted paths as well as unrooted partial paths ('sql/file.sql').
 * Remove `ResolutionFolder`. It no longer serves a purpose.
These together would make the simplest first scenario Just Work™

**Comment by dmitry-a-morozov** [comment]
I'll have a look. It will take take some time because I'm swamped with my primary work.

**Comment by rojepp** [comment]
Would you accept a PR with the changes I've outlined?

**Comment by dmitry-a-morozov** [comment]
I don't use *.sql file much so it's hard for me to make this call.
Probably you're right.
Here is relevant discussion
https://github.com/fsprojects/FSharp.Data.SqlClient/issues/64
Let me check first if "ResolutionFolder" param is used in any of Tachyus prod projects.

**Comment by rojepp** [comment]
@dmitry-a-morozov I went ahead and implemented it. Feel free to ignore if you think its a bad idea. :)

**Comment by dmitry-a-morozov** [comment]
Cool, 
Thanks for help.
