### ISSUE TITLE
Better support for statements that don't have a return value

### ISSUE THREAD

**Issue by rojepp** [fsprojects/FSharp.Data.SqlClient#119]
Sometimes you just want to perform an action and not care about the result. For example
```fsharp
type ClearTable = SqlCommandProvider<"delete from ExportedAssessments", cn>
let clearExports (cn:string) = 
    use c = new ClearTable(cn)
    c.Execute() |> ignore
```

This query fails for me with an InvalidCastException, at least on OSX. It compiles though. 
To get this query to run I have to
```fsharp
type ClearTable = SqlCommandProvider<"delete from ExportedAssessments;select 1 as monkey", cn>
```

**Comment by dmitry-a-morozov** [comment]
Fixed in ver 1.6.2
This was nasty bug.
In following line pattern didn't match for mixture of 3.0 and 3.1 F# core.
https://github.com/fsprojects/FSharp.Data.SqlClient/blob/104ca6be317dd752817b1272eacdeb69e5d7bb63/src/SqlClient/ISqlCommand.fs#L96
Thank you for testing and giving me a hard time :)
