### ISSUE TITLE
Performance

### ISSUE THREAD

**Issue by vasily-kirichenko** [fsprojects/FSharp.Data.SqlClient#124]
Could we use some other option to pass schema through quotation boundaries? 

![image](https://cloud.githubusercontent.com/assets/873919/7365110/bf5c43d2-ed95-11e4-856c-2caa5977ba74.png)

**Comment by dmitry-a-morozov** [comment]
Why?

**Comment by dmitry-a-morozov** [comment]
any particular reason you closed this ticket?

**Comment by dmitry-a-morozov** [comment]
check out ver 1.7.0-beta. I will promote it to final in 2-3 days.
