### ISSUE TITLE
undeclared parameter cannot be used more than once

### ISSUE THREAD

**Issue by jackfoxy** [fsprojects/FSharp.Data.SqlClient#13]
It appears you cannot use the same parameter more than once. 

Comment out the second occurence:

    --OR city LIKE @startsWith

and it builds.

Error	6	The type provider 'FSharp.Data.SqlClient.SqlCommandTypeProvider' reported an error: The undeclared parameter '@startsWith' is used more than once in the batch being analyzed.	

    [<Literal>]
    let sqlCityCounty = @"
                    SELECT DISTINCT
                        streetName = null, 
                        streetAddress = null, 
                        postalCode = null, 
                        listingID = null, 
                        mlsID = null,
                        classID = null,
                        neighborhood = null,
                        countryCode,
                        state,
                        county,
                        city
                    FROM tbMLSQuickLocationListingCount WITH (NOLOCK)
                    WHERE 
                        (
                            county LIKE @startsWith
                            OR city LIKE @startsWith                                           
                        ) 
                        AND locationType = 'City'
                        AND MLSID IN (select * from dbo.ConvertCommaSeparatedStringToTableOfInts(@mlsIDList))
                        AND CASE WHEN (MLSID = 10 AND companyID = @companyID) OR MLSID <> 10 THEN 1 ELSE 0 END = 1"

    type QueryCityCounty = SqlCommand<sqlCityCounty, ConnectionStringName="staging", ResultType = ResultType.Records, ConfigFile="AutoComplete.config">
    let cmd1 = QueryUserMLS(startsWith = "7L%", mlsIDList = "1,2,3", companyID = 1)

**Comment by dmitry-a-morozov** [comment]
fixed in ver 1.7.6

**Comment by geandbe** [comment]
Looks like the issue reopen is due. TP fails to accept the following query:
    
    .....................
    WHERE <predicate>
    AND (@Param = '' OR [Field] = @Param)

with diagnostics "An item with the same key has already been added".

**Comment by rojepp** [comment]
@geandbe The workaround I posted above doesn't work?

**Comment by geandbe** [comment]
Sure it does, but workaround <> closed issue, right?

**Comment by geandbe** [comment]
And also this workaround may seriously mess up execution plan.

**Comment by cmeeren** [comment]
The workaround works, but is this not possible to fix? Using e.g. `@input = '' OR @input = 'asd'` in a normal SQL script works fine without declaring it, but fails using using this type provider.
