### ISSUE TITLE
unify SqlProgrammabilityProvider and SqlCommandProvider ctors

### ISSUE THREAD

**Issue by dmitry-a-morozov** [fsprojects/FSharp.Data.SqlClient#131]
Currently commands generated by SqlProgrammabilityProvider do have constructor that accept live connection.
Need to make this inform with SqlCommandProvider
new: (?SqlConnection * ?SqlTransaction * commandTimeout: int -> #ISqlCommand)

**Comment by smoothdeveloper** [comment]
Looking forward for that, I can't use SqlProgrammabilityProvider with this code:

```fsharp
  static member inline Create (createCommand: unit -> SqlCommand) : 'a =
    let dummyCommand = createCommand()
    let cx = dummyCommand.Connection
    let tx = dummyCommand.Transaction
    let timeout = dummyCommand.CommandTimeout
    (^a : (new : SqlConnection * SqlTransaction * int -> ^a) (cx, tx, timeout)) 
```

but I could definitely use it if this was implemented.

I was willing to implement the changes but saw that there was a temp branch with a bit of refactoring and this implemented.

Let me know if you'd like me to make a branch with only this.

Thanks

**Comment by dmitry-a-morozov** [comment]
Already implemented. 
https://github.com/fsprojects/FSharp.Data.SqlClient/blob/temp/src/SqlClient/SqlProgrammabilityProvider.fs#L202
https://github.com/fsprojects/FSharp.Data.SqlClient/blob/temp/src/SqlClient.Tests/ProgrammabilityTests.fs#L121

Will be available in the next release. 
Soon.

**Comment by dmitry-a-morozov** [comment]
@reidev275 @smoothdeveloper check-out ver 1.7.0-beta. I will promote it to final in 2-3 days.

**Comment by smoothdeveloper** [comment]
@dmitry-a-morozov thanks for update.

I'm updating my code but there are few places I'm using .AsSqlCommand because I need to set the parameters dynamically in my code to queries I have defined (passing a dictionary of arguments).

Is there any alternative to replace my usage of AsSqlCommand? I just want to avoid to have to duplicate the sql statements by having to create my own untyped commands.

Maybe if you can't have AsSqlCommand anymore for some reason you can expose the CommandText and parameter list in way which allows dynamic inspection so it's possible to create our own AsSqlCommand? It feels that the API footprint is actually larger if you have to expose those things rather than the self contained AsSqlCommand.

**Comment by dmitry-a-morozov** [comment]
I thought you're using ISqlCommand.Raw

**Comment by smoothdeveloper** [comment]
ISqlCommand.Raw would definitely work, I'm not sure how to convert an instance of SqlCommandProvider to ISqlCommand though? I tried ```:?>```

I could replace the usages I had anyways as in those places I could actually do without reflection on command parameters, able to create commands from SqlProgrammabilityProvider with the code in my previous comment :)

Thanks for your help.

**Comment by rojepp** [comment]
You convert the provided type to ISqlCommand, not SqlCommandProvider. Does this help?

**Comment by dmitry-a-morozov** [comment]
yes. examples are below
https://github.com/fsprojects/FSharp.Data.SqlClient/blob/master/src/SqlClient.Tests/TypeProviderTest.fs#L21
https://github.com/fsprojects/FSharp.Data.SqlClient/blob/master/src/SqlClient.Tests/TypeProviderTest.fs#L32
https://github.com/fsprojects/FSharp.Data.SqlClient/blob/master/src/SqlClient.Tests/TypeProviderTest.fs#L178
https://github.com/fsprojects/FSharp.Data.SqlClient/blob/master/src/SqlClient.Tests/TransactionTests.fs#L19

**Comment by smoothdeveloper** [comment]
@dmitry-a-morozov in last release of provider with this change:

https://github.com/fsprojects/FSharp.Data.SqlClient/blob/e01b96a87df0ca2d9cb89ccdde02ae9e97c83bcc/src/SqlClient/ISqlCommand.fs#L63

this break my infrastructure code:

```fsharp
 static member inline Create (createCommand: unit -> SqlCommand) : 'a =
    let dummyCommand = createCommand()
    let cx = dummyCommand.Connection
    let tx = dummyCommand.Transaction
    let timeout = dummyCommand.CommandTimeout
    (^a : (new : SqlConnection * SqlTransaction * int -> ^a) (cx, tx, timeout)) 
```

as there is no more constructor to pass connection, transaction and timeout.

How can I replace my function with newest release which takes a `DesignTimeConfig` object as first argument?

Just as a bit of context, in my code, I never pass connection, transaction or command timeout around, I instead pass a "command factory" functor which initializes a new command with correct context/settings.

**Comment by dmitry-a-morozov** [comment]
Hi @smoothdeveloper 
I apologize for breaking change but I believe it's for better.

Starting v1.8 there are 2 ctors on every instance of command
 - (^a : (new : string -> ^a) "server=.;database=AdventureWorks;Trusted_Connection=yes") 
 - (^a : (new : option<SqlConnection> * option<SqlTransaction> * option<int> -> ^a) (conn, tx, timeout)) 

Ctor #2 allows optionally reconfigure any available property on command. 
Ctor #1 is most commonly used in IOC.

**Comment by dmitry-a-morozov** [comment]
@vasily-kirichenko @smoothdeveloper 
Do you it will be a good idea to have single ctor with following type signature
```FSharp
[<RequireQualifiedAccess>]
type Connection = 
    | String of string
    | Instance of SqlConnection
    | Tx of SqlTransaction

//ctor type signature
new : option<Connection> * int -> ^Command
```

**Comment by smoothdeveloper** [comment]
@dmitry-a-morozov thanks for the quick update, I'll try the new constructor, I welcome changes to this great library and hope I won't be stuck with updates.

In your proposition, why is the first parameter optional?

For a single constructor, I'd be very happy if there was a way to pass `unit -> SqlCommand` as an extra option, I think it could look like this:

```fsharp
[<RequireQualifiedAccess>]
type CommandContext = 
    | String of string * int
    | Instance of SqlConnection * int
    | Tx of SqlTransaction * int
    | CommandFactory of unit -> SqlCommand

//ctor type signature
new : CommandContext -> ^Command
```

I don't know if that makes sense to you / users of the library.

**Comment by dmitry-a-morozov** [comment]
@vasily-kirichenko @smoothdeveloper
I implemented DU
https://github.com/fsprojects/FSharp.Data.SqlClient/blob/4631e581a3acb3ac942cf78ae6f5d93a71804824/src/SqlClient/Configuration.fs#L22
So now there are 2 ctors on generated command types:
  1. accepts mandatory connection string most often used for IOC/configuration factories 
  2. has 2 _optional_ params: connection of type ```Connection``` and ```commandTimeout```. 

```Connection``` DU is located under ```FSharp.Data.SqlClient``` namespace. 

So either open this namespace or use ```SqlClient.Connection``` prefix of you have only ```FSharp.Data``` namespace open.

Examples from tests
https://github.com/fsprojects/FSharp.Data.SqlClient/blob/4631e581a3acb3ac942cf78ae6f5d93a71804824/src/SqlClient.Tests/TypeProviderTest.fs#L33

https://github.com/fsprojects/FSharp.Data.SqlClient/blob/4631e581a3acb3ac942cf78ae6f5d93a71804824/src/SqlClient.Tests/TransactionTests.fs#L63


Please, try v1.8.1-alpha
https://www.nuget.org/packages/FSharp.Data.SqlClient/1.8.1-alpha

I will promote it to release of you like it.
