### ISSUE TITLE
SqlCommandProvider with T-SQL file doesn't work in fsi

### ISSUE THREAD

**Issue by neolem** [fsprojects/FSharp.Data.SqlClient#141]
The following code compiles and runs in F5. However, it fails when run in fsi.exe (F# interactive). 

```type t = SqlCommandProvider<"Applications.sql", connStr>```

```Applications.sql``` contains the following t-sql and is located in the same folder as the .fsx script file.
```
Select 'Col1' As Col1, 'Col2' As Col2
```
The error I get is,

> Script1.fsx(19,10): error FS3033: The type provider 'FSharp.Data.SqlCommandProvider' reported an error: Could not find stored procedure 'Applications.sql'.

>The metadata could not be determined because every code path results in an error; see previous errors for some of these.

Is there something that I am missing perhaps?

**Comment by neolem** [comment]
I did some investigation. It seems when executing the type provider from within the fsi.exe, the default folder it looks for is in the Scripts folder of the current project root folder. Maybe an option would be to default to ```System.Environment.CurrentDirectory```, since in .fsx script files we usually do System.Environment.CurrentDirectory <- __SOURCE_DIRECTORY__ ...

**Comment by neolem** [comment]
I have managed to resolve this with the code below.

```[<Literal>]
let resFolder = __SOURCE_DIRECTORY__ + "\\T-SQL"

let app() =
    let a = new SqlCommandProvider<"test1.sql", connStr, ResolutionFolder = resFolder>()
    a.Execute()
```
The above executes okay in both the fsi.exe and F5.

**Comment by dmitry-a-morozov** [comment]
Sorry for delayed response - I was on a short vacation.
I'm glad you found a way to resolve the issue.
You could also consider something like
http://stackoverflow.com/a/10917385/1603572
