### ISSUE TITLE
404 on SqlProgrammabilityProvider

### ISSUE THREAD

**Issue by dsyme** [fsprojects/FSharp.Data.SqlClient#143]
The front page link for SqlProgrammabilityProvider gives me a 404 http://fsprojects.github.io/FSharp.Data.SqlClient/sqlprogrammabilityprovider.quickstart.html

**Comment by dmitry-a-morozov** [comment]
I removed the broken link. 
Revamping docs is on my roadmap.
Probably after I'll ship v2.
