### ISSUE TITLE
Broken XML doc

### ISSUE THREAD

**Issue by vasily-kirichenko** [fsprojects/FSharp.Data.SqlClient#146]
![image](https://cloud.githubusercontent.com/assets/873919/8822022/e27eeca8-306a-11e5-821c-008a90d33ed8.png)

**Comment by dmitry-a-morozov** [comment]
Run this query
https://gist.github.com/dmitry-a-morozov/b854ebf2aa2c5229765d
against a table you use. 
Send me back results.

**Comment by dmitry-a-morozov** [comment]
I was able to repro this issue.
Unfortunately, I cannot write any unit tests :(
All manual testing.

**Comment by dmitry-a-morozov** [comment]
fixed in ver 1.7.6
