### ISSUE TITLE
how to use plain DataReader to populate typed records?

### ISSUE THREAD

**Issue by smoothdeveloper** [fsprojects/FSharp.Data.SqlClient#149]
I'm looking for a way to use my own custom commands and reuse record types defined with SqlCommandProvider provided types.

```fsharp
type FooQuery = SqlCommandProvider<"",connectionString>

let command : System.Data.IDbCommand = getCommand() // the recordset has same shape as FooQuery.Row
use reader = command.ExecuteReader()
let rows = ?? // Do something with FooQuery and reader to get a FooQuery.Row seq
```

I know there was once the possibility to do that which was exhibited in the samples but I can't find it anymore.

If this still exists, please let me know how I can achieve what I shown in sample code above, and maybe it's worth to create a FAQ page in documentation with such sample code?

Thanks a bunch!

**Comment by dmitry-a-morozov** [comment]
You still can do it. Example is here
https://github.com/fsprojects/FSharp.Data.SqlClient/blob/2fca2804faaca24bc602a9a18f9740ca0186141b/src/SqlClient.Tests/SqlCommand.fsx#L170

**Comment by smoothdeveloper** [comment]
Thanks @dmitry-a-morozov 

I've put minor addition in the FAQ to expose this feature in the documentation, can you check if PR #150 is appropriate?

**Comment by dmitry-a-morozov** [comment]
Done. Thank you for the contribution.

**Comment by smoothdeveloper** [comment]
@dmitry-a-morozov it would still be nice to have the provider expose a `.ExecuteReader` method IMHO, taking the same arguments as the plain `.Execute` one, this allows to keep the safety of parameter passing.

**Comment by dmitry-a-morozov** [comment]
That exactly what is ResultType.DataReader for.

**Comment by smoothdeveloper** [comment]
@dmitry-a-morozov, saw your other answer for DataTable, do you foresee a problem if we were to leave the option open on a SqlCommandProvider instance with different methods?

Having to define several instances of SqlCommandProvider with different names just to leverage different result types is a bit cumbersome, if there is no technical limitation, why won't we leave the choice at usage site instead (we can still support the static TP parameter for the plain Execute method).

I'd be happy to contribute a PR if you think those changes are doable and benefits the library.
