### ISSUE TITLE
[AliasType].Record causes build failure when [FullPath].Record does not

### ISSUE THREAD

**Issue by reidev275** [fsprojects/FSharp.Data.SqlClient#151]
A common practice of mine is to have function that maps a SqlProgrammabilityProvider record type into a record type I've created.  When defining the type in the mapping function the build fails unless I start the type name from the SqlProgrammabilityProvider base type.  This is probably better explained with code:

    type Db = SqlProgrammabilityProvider<"name=db">
    type MySproc = Db.dbo.spMySproc

    type Foo = {
        Bar : string
    }

    let toFoo (x : MySproc.Record) = { Bar = x.Bar }
    //The type 'Record' is not defined

    let toFoo (x : Db.dbo.spMySproc.Record) = { Bar = x.Bar }
    //no error

** edited to fix typo mentioned later **

**Comment by dmitry-a-morozov** [comment]
Hmm. I cannot reproduce that.
I works as expected on my machine.

**Comment by reidev275** [comment]
I'm on Windows 7 with VS2012.  I meant to put that in the initial comment.  May be something with my setup.

**Comment by dmitry-a-morozov** [comment]
ok. I will  need to setup both to debug it.
Any chance you can do it for me?

**Comment by reidev275** [comment]
would love to,  where do I start?

**Comment by dmitry-a-morozov** [comment]
I installed VS2012 on my win10 machine but still cannot repro.
Also, in the sample code above you meant
```fsharp
let toFoo (x : Db.dbo.spMySproc.Record) = { Bar = x.Bar }
```
not
```fsharp
let toFoo (x : Db.dbo.spMySproc) = { Bar = x.Bar }
```
correct?

**Comment by reidev275** [comment]
Yep, that was a typo on my part.

May just be something wonky on my box.  It's not a huge issue, esp if you can't reproduce.

**Comment by andredublin** [comment]
I'm able to reproduce this error on win8.1 using vs2013
```
module Cars = 
    open FSharp.Data
    
    type CarsDatabase = SqlProgrammabilityProvider<"name=CarsDatabase">
    
    // The type Record is not defined
    let toAutomobile (record : CarsDatabase.dbo.wspGetAutomobiles.Record) : Car = 
        { ID = record.ID
          Make = record.Make
          Model = record.Model
          Year = record.Year }
    ```

**Comment by dmitry-a-morozov** [comment]
@andredublin Can you create a sample repro project?

**Comment by andredublin** [comment]
https://github.com/andredublin/fsharp-webapi-example

**Comment by reidev275** [comment]
I believe that's a slightly different issue than I had.  In my case your example works, but the following would fail.

    type GetAutomobiles = CarsDatabase.dbo.wspGetAutomobiles
    let toAutomobile (record : GetAutomobiles.Record) = ()

**Comment by dmitry-a-morozov** [comment]
close because I cannot repro this
