### ISSUE TITLE
Feature request: introspection of provided SqlCommand

### ISSUE THREAD

**Issue by smoothdeveloper** [fsprojects/FSharp.Data.SqlClient#156]
It would be nice to be able to introspect elements constituting a SqlCommand:
* CommandText containing the raw sql code (not a prepared statement that we can obtain via ```ISqlCommand .Raw```)
* Parameters containing the list of parameter descriptors (should expose the .NET type of parameter and parameter direction)

I'm facing cases where I need to remove ```with result sets``` of my sql code (supporting sql server < 2012), and to do so i have to copy the content of the .sql file in the code.

Also, having ability to inspect parameters programatically would be helpful, starting with at least the CommandText.

This comes handy with the ```ToRecords``` described in the faq.

```fsharp

type MyCommand = SqlCommandProvider<"somefile.sql", "connectionstring">

printfn "%s" MyCommand.CommandText
// prints contents of somefile.sql
printfn "%A" MyCommand.Parameters 
(* [
  ParameterDescriptor { Name = "parameter1"; Type = typeof<int>; Direction = In },
  ParameterDescriptor { Name = "parameter2"; Type = typeof<string>; Direction = In }
]
*)
```

Is that something that could fit in the library?

Would a PR be helpful to get this integrated?

**Comment by dmitry-a-morozov** [comment]
What's wrong with getting both ```CommandText``` and ```Parameters``` collection via ```ISqlCommand.Raw```?

**Comment by smoothdeveloper** [comment]
@dmitry-a-morozov, you are right it has the expected text and parameters defined.

I guess it's the fact that ISqlCommand type doesn't show anywhere in intellisense.

```fsharp
open FSharp.Data
// ...
let cmd = new CommandType()
let raw = (cmd :> ISqlCommand).Raw // if I type ISql and look for completions, nothing shows up

```
and that we get a warning every where ISqlCommand appears in the code.

I'll update the FAQ to expose this work around.
