### ISSUE TITLE
Oracle support?

### ISSUE THREAD

**Issue by ptrelford** [fsprojects/FSharp.Data.SqlClient#157]
It would be great if the SqlClient could support Oracle as well as MS SQL Server. Would this be feasible within the existing project structure or better handled in a new project?

**Comment by rojepp** [comment]
This TP uses two Sql Server specific procedures to get the metadata for an arbitrary query: sys.sp_describe_undeclared_parameters and sys.sp_describe_first_result_set. 

For Oracle, one way to discover the resulting type could be to wrap the entire query into a temp table, and inspect the structure of that, provided there is only one result set. This is also a limitation for Sql Server. http://dba.stackexchange.com/a/75124
I don't have any suggestions for discovering the types/names of parameters.

**Comment by dmitry-a-morozov** [comment]
Keep in mind that I'm not an Oracle expert. 
  * Technology

_SqlCommandProvider_ support for Oracle requires a replacement for ```sys.sp_describe_undeclared_parameters``` and ```sys.sp_describe_first_result_set```.
As @rojepp correctly pointed out above __limited__ version of result set types discovery can be done using something like http://stackoverflow.com/questions/9132556/obtain-column-information-of-result-set-returned-via-a-ref-cursor-parameter. And it seems like there is no obvious alternative for  ```sys.sp_describe_undeclared_parameters``` which reduces a value of library significantly. 
_SqlProgrammabilityProvider_ mostly likely can support Oracle. 
_SqlEnumProvider_ is already can be used with any ADO.NET supported data source.
  * Packaging 

Supposing technical difficulties outlined above can be resolved (which is big _if_), refactoring the library to support more than one database type will lead to ~30% increase in code complexity at least. Differences between database capabilities and client libraries will lead to conditional types/methods/params generation like:SqlTransaction vs OracleTransaction, Sql Server TVP, built-in paging, types cache update based on XE etc. 

I think the best solution is to create separate library of type providers for Oracle.

  * Development effort/resources 

This is probably most important point. Maintenance/development of this library takes a lot of my time.  I simply don't/won't have bandwidth to upgrade it for Oracle support.
