### ISSUE TITLE
Explicit file URIs for command text

### ISSUE THREAD

**Issue by dmitry-a-morozov** [fsprojects/FSharp.Data.SqlClient#163]
SqlCommand supports ability to pass file path (absolute or relative) as ```CommandText``` parameter. The provider attempts to look up file by this name and if one is not found assumes that provided value is T-SQL. These leads to very confusing error messages about invalid T-SQL in cases when file path mis-typed or cannot be found (for example issue #123). 
New syntax will expect explicit file uri e.g.
"file:///C:/Users/dsyme/Documents/GetOrders.sql"
or 
"file:///../MyFolder/GetOrders.sql"
This will make error messages more meaningful.

**Comment by dmitry-a-morozov** [comment]
not going to work

**Comment by rojepp** [comment]
Out of curiosity, why won't it work? @dmitry-a-morozov

**Comment by dmitry-a-morozov** [comment]
A little bit of context. 
The primary objective is to improve an experience when developer meant to use file but mistypes path. Currently in such case file probing logic falls back to treating content of CommandTextOrFile parameter as T-SQL throwing something irrelevant like "SQL batch cannot be analyzed because of errors ... "  
It gets especially confusing in case of
https://github.com/fsprojects/FSharp.Data.SqlClient/issues/123

The file path processing is not root cause of https://github.com/fsprojects/FSharp.Data.SqlClient/issues/123 but still if we could provide more meaningful error message like "File script.sql is not found" that will be improvement. 

So plan was to enforce explicit prefix "file://" which makes it file schema URI. I hoped it will remove ambiguity and guess work. 
This works fine for real absolute file path like 
"file:///C:/Users/mitekm/Documents/GitHub/FSharp.Data.SqlClient/src/Scripts/Scratchpad.fsx"
But in typical scenario developers use relative path optionally combine with custom "ResolutionFolder".
but strictly speaking URI like 
"file://SQL/myscript.sql" is considered absolute. This makes this concept heavy overloaded. 
It gets trickier if user puts something like "file:///../SQL/myscript.sql"

Considering it's a breaking change I decided to back off.

**Comment by rojepp** [comment]
Good explanation, thanks! I agree it looks kind of weird the relative path and file protocol.

**Comment by dmitry-a-morozov** [comment]
I still want to make the file probing logic a little smarter. 
I'll ship a new version and collect feedback. 
If it will do more harm than help I'll rollback to current version.
BTW, https://github.com/fsprojects/FSharp.Data.SqlClient/issues/123 will be solved by making SqlCommand generative types. 
*IF* it will work out I'll probably prohibit using file references in SqlClient (former SqlProgrammability) at all.

**Comment by rojepp** [comment]
SqlClient can't be generated too?

**Comment by dmitry-a-morozov** [comment]
As I described in https://github.com/fsprojects/FSharp.Data.SqlClient/issues/162
their functionality will largely overlap so I want to differentiate them by optimizing for different scenarios.
You can see progress on SqlClient here
https://github.com/fsprojects/FSharp.Data.SqlClient/blob/V2/src/SqlClient.Tests/CreateCommand.fs

Somebody else helps me to make SqlCommand generative types. The work is not finished yet. So it's inconclusive at this point. Also, I won't ship V2 until F# team will fix intellisense issues for statically parameterized TP methods. Cause it unusable in current form.
