### ISSUE TITLE
Error thrown for Azure SQL Database, "The input sequence was empty", but not for on-prem SS instance

### ISSUE THREAD

**Issue by CalvinDale** [fsprojects/FSharp.Data.SqlClient#166]
The following code throws *"The type provider 'FSharp.Data.SqlCommandProvider' reported an error: The input sequence was empty."* when connected to an Azure SQL Database but not when connected to an on-premises SQL Server 2014 CU4 instance. I'm not sure what's going on here since this is my first attempt to use *SqlCommandProvider*. And so as a newbie, even though I suspect that it has no relevance to this error, I will nevertheless mention that both databases have the identical data.

    [<Literal>]
    let connectionString = "name=CatalogContext1"
    
    type SearchModel = 
        { BrakeDrumNumber : string
          Description : string
          BomDescription : string
          BomMaterial : string
          Status : string
          StatusId : int
          IsPublic: bool }
    
    type SearchByConMetFldsCmdPvdr = SqlCommandProvider< "SELECT * FROM BrakeDrum.ft_SelectBySearchTokens_ConMetFieldsOnly(@TokenTable)", connectionString, ResultType.Records >
    
    type SearchTokenTableType = SearchByConMetFldsCmdPvdr.SearchTokenTableType

    let Search(searchText : string) = 
        let tokens = 
            searchText.Split(' ')
            |> Array.filter (fun token -> token.Length > 2)
            |> Array.map (fun token -> SearchTokenTableType(token))
        
        let searchCommand = new SearchByConMetFldsCmdPvdr()
        
        let records =  searchCommand.Execute(tokens)
                       |> Seq.map (fun r ->  { BrakeDrumNumber = r.BrakeDrumNumber
                                               Description = r.Description
                                               BomDescription = r.BomDescription
                                               BomMaterial = r.BomMaterial
                                               Status = r.Status
                                               StatusId = r.StatusId
                                               IsPublic = r.IsPublic })
                       |> Seq.toArray
        
        records

-

	CREATE TYPE dbo.SearchTokenType FROM NVARCHAR(30) NOT NULL;
	GO
	CREATE TYPE dbo.SearchTokenTableType AS TABLE (
		Token dbo.SearchTokenType
	);
	GO
	CREATE FUNCTION BrakeDrum.ft_SelectBySearchTokens_ConMetFieldsOnly (@TokenTable dbo.SearchTokenTableType READONLY)
	RETURNS TABLE
	RETURN
		SELECT TOP 10 b.BrakeDrumNumber, p.[Description], p.BomDescription, p.BomMaterial, b.IsPublic, u.Name AS [Status], p.StatusId
		FROM BrakeDrum.BrakeDrums b
		JOIN Part.Parts p ON p.PartNumber = b.BrakeDrumNumber
		JOIN BrakeDrum.Sizes s ON s.Id = b.BrakeDrumSizeId
		JOIN Part.Statuses u ON u.Id = p.StatusId
		WHERE (
			ISNUMERIC(b.BrakeDrumNumber) = 1 AND
			b.ManufacturerId = 2 AND -- ConMet
			((SELECT COUNT(Token)
			FROM @TokenTable
			WHERE (
					(CAST(CHARINDEX(Token, b.BrakeDrumNumber) AS INT) > 0)
				 OR (CAST(CHARINDEX(Token, p.[Description]) AS INT) > 0)
				 OR (CAST(CHARINDEX(Token, p.BomDescription) AS INT) > 0)
				 OR (CAST(CHARINDEX(Token, p.BomMaterial) AS INT) > 0)
				 OR (CAST(CHARINDEX(Token, s.SearchTerm) AS INT) > 0)
			)) = (SELECT COUNT(Token) FROM @TokenTable))
		) 
		ORDER BY LEN(b.BrakeDrumNumber), b.BrakeDrumNumber

**Comment by dmitry-a-morozov** [comment]
I assume this happens at design time, right?

**Comment by CalvinDale** [comment]
yes

**Comment by dmitry-a-morozov** [comment]
I tried to replicate the issue using somewhat similar database definitions but no luck.
I know it's a lot to ask but any chance you can help me to debug this or provide self-contained repro?

**Comment by CalvinDale** [comment]
I just removed all add-ins and repaved VS. The issue seems to have resolved itself.
