### ISSUE TITLE
publish strong named assemblies on nuget

### ISSUE THREAD

**Issue by smoothdeveloper** [fsprojects/FSharp.Data.SqlClient#167]
Would it be considered to sign assemblies that are published on nuget?

Currently if I want to use FSharp.Data.SqlClient in an application which is signed, I need to make my own build which hinders updating the library to latest release.

What are the current concerns with signing assemblies and how can I help to address those?

**Comment by dmitry-a-morozov** [comment]
I have nothing in particular against signing.  
I don't have much experience in this area.
Are there any downsides?

**Comment by smoothdeveloper** [comment]
These are downsides I'm aware of:

* the qualified name (with publictoken) should be used if InternalsVisibleTo is used for some purpose (I recall it's used for tests)
* can't have any unsigned reference
* force usage of binding redirects

**Comment by dmitry-a-morozov** [comment]
I'm really puzzled on this one. 
Do you have an example of well known F# OSS or .NET OSS library that is strongly signed?

**Comment by dmitry-a-morozov** [comment]
@smoothdeveloper Here interesting and relevant post on the subject
http://blog.marcgravell.com/2014/06/snk-we-need-to-talk.html

What's your particular reason to consume strongly signed assemblies?

**Comment by smoothdeveloper** [comment]
@dmitry-a-morozov thanks for coming back on the matter.

The reason I need it to be strongly signed is that I intend to ship it with signed application at my work, I think usage of signed assemblies in my case pertains to _because that is what their corporate policy says they must do_.

It would rock if nuget had an option to post sign assemblies.

If it's not something you want to spend time with (which I understand) but you are open to get the assembly signed, I can definitely give a look at it by checking how other nuget packages that are signed deal with it (I have no experience on nuget package publishing).

**Comment by dmitry-a-morozov** [comment]
My primary concern that once I buy into strong naming I wont't be able to take dependency on any unsigned assembly which will be big limitation.
Probably the best solution is to have 2 versions of the library on nuget - signed and unsigned.
How hard for you to keep building from sources? 
I can probably do better job by tagging releases.

**Comment by smoothdeveloper** [comment]
@dmitry-a-morozov I'll work around this by building my own releases. Thanks.
