### ISSUE TITLE
Wanted to share workaround for compile time 'The metadata could not be determined because statement 'Exec dbo.A' in procedure 'B' causes indirect recursion.'

### ISSUE THREAD

**Issue by lefthandedgoat** [fsprojects/FSharp.Data.SqlClient#168]
I started to receive a compile time error yesterday (without making any code changes) because the DBAs made a change in environment I use in my design time connection string.

'The metadata could not be determined because statement 'Exec dbo.A param param' in procedure 'B' causes indirect recursion.'

They were improving a stored procedure that did logging and introduced this problem.

We determined it was because Proc A (logging proc) was calling Proc B, if Proc B had a problem it would call Proc A, thus introducing a circular reference.  In reality it would not cause any problems but it was causing my compiles to fail.

After some digging we found out that its an error from the `sp_describe_first_result_set` proc use by SqlClient.  The proc I was calling used the error logging proc and it was picking up the circular reference from it.

To work around we added this towards the top of our proc:

`SELECT TOP 1 "" as nothing from dbo.SomeTable`

I guess this tricked `sp_describe_first_result_set` enough to get us past the problem.

Just wanted to share.  Thanks for working on such a great project!

**Comment by dmitry-a-morozov** [comment]
Thanks for feedback !

I thought I already doing something similar

https://github.com/fsprojects/FSharp.Data.SqlClient/blob/890ccac41eb468c77d3f699318cd7f1c119c9544/src/SqlClient/DesignTime.fs#L207

https://github.com/fsprojects/FSharp.Data.SqlClient/blob/5beea0f1b99de32a38e7df6f2f7d0edf01087bac/src/SqlClient/SqlClientExtensions.fs#L372

Did you use SqlCommandProvider or SqlProgrammabilityProvider to invoke the stored procedure?

Also, I don't understand how you can use "SELECT TOP 1 * " when it comes to stored procedure?

**Comment by lefthandedgoat** [comment]
This is what my code looked like
```
[<Literal>]
let updateSomethingQuery = """
Exec dbo.SomeProc @Param1 = @param1, @Param2 = @param2
"""

type UpdateSomethingQuery = SqlCommandProvider<updateSomethingQuery, designTimeConnectionString>

let updateSoemthing param1 param2 =
  let cmd = new UpdateSomethingQuery(runTimeConnectionString())
  cmd.Execute(param1 = param1, param2 = param2) |> ignore
```

The proc looked something like this

```
ALTER Procedure [dbo].[SomeProc]
        @param1     INT,
	@param2 nvarchar(16)
Declare	 
	 @calculated1 as varbinary(64)
	,@calculated2 as varbinary(64)

--Work around 
SELECT TOP 1 '' as nothing from dbo.SomeTable

Set @calculated1 = --do stuff
Set @calculated2 = --do more stuff


exec [dbo].[ExistingProcThatUsesTheLoggingWithCircularReference] 
	  @Param1 = @calculated1
	, @Param2 = @calculated2
	, @Param3 = 1
```

So by placing the dummy SELECT statement prior to the execution of `[ExistingProcThatUsesTheLoggingWithCircularReference]`, the `sp_describe_first_result_set` proc would get the result of the SELECT statement instead of doing further inspection of called proc and hitting the circular reference. (I think)

**Comment by dmitry-a-morozov** [comment]
Interesting. Changing stored procedure definition to make it work with SqlCommandProvider is not very nice experience. 
1) Can you debug and see if it goes for FallbackToSETFMONLY. As a shortcut you can check if following t-sql executes without errors
```SQL
DECLARE 
    @param1 AS ...,
     @param2 AS ...
SET FMTONLY ON
Exec dbo.SomeProc @Param1 = @param1, @Param2 = @param2
SET FMTONLY OFF

```
2) Can you try SqlProgrammabilityProvider and see if it works better?

**Comment by lefthandedgoat** [comment]
I haven't had a chance to look into this, but its started to affect UPDATE and DELETE statements (I think due to a trigger that uses the recursive proc).

I have never worked with the source of a TP.  How do you debug the compile time aspect of it?  I will try to create a sample db that has these problems and work on it.

**Comment by dmitry-a-morozov** [comment]
Debugging type provider compile time aspect is the very hard. 
You need source code.
Maybe I will add some kind of logging like in RProvider. 
I just don't have capacity to do to at the moment.

**Comment by lefthandedgoat** [comment]
Ok as long as System.Console.Writeline works then I can make an attempt at figuring it out!
