### ISSUE TITLE
Doesn't read connection strings from referenced configSource="app.ConnectionStrings.config" file

### ISSUE THREAD

**Issue by CalvinDale** [fsprojects/FSharp.Data.SqlClient#171]
For a suggestion, it would be nice if the `FSharp.Data.SqlClient` library read connection strings from a referenced file. 

For example:
```
web.config

...
<connectionStrings configSource="app.ConnectionStrings.config"></connectionStrings>
...


app.ConnectionStrings.config
...
<connectionStrings>
  <add name="CatalogContext"
       connectionString="Data Source=(LocalDB)\MSSQLLocalDB;Initial Catalog=Catalog;Integrated Security=True;"
       providerName="System.Data.SqlClient" />
</connectionStrings>
```

This technique can be useful for dealing with password-containing connection strings or when different connection strings are used on different machines, etc.

**Comment by dmitry-a-morozov** [comment]
It should work as is. The type provider uses standard .NET BCL to read config info.
It knows to merge ref config file into main one and read it as one whole.

**Comment by dmitry-a-morozov** [comment]
Does it work for you?

**Comment by CalvinDale** [comment]
I am planning to try this again. Unfortunately I haven't yet been able to carve out time to pursue it. I have it flagged to report back when I do finally get around to testing it again. But when i tried it before it didn't work.

**Comment by CalvinDale** [comment]
I verified that it's working. I couldn't reproduce the situation when it didn't work.

**Comment by dmitry-a-morozov** [comment]
One limitation that you need to be aware of is that included file i.e. app.ConnectionStrings.config should be in same folder or below. It cannot be in folder above even if you use relative path in app.config. "..\MyFolder\myfile.config" won't work

Another thing to keep in mind is that at run-time included file should be deployed along side with app.config/web.config
