### ISSUE TITLE
Generated Types for SqlProgrammabilityProvider: Does not support non-dbo

### ISSUE THREAD

**Issue by jamessdixon** [fsprojects/FSharp.Data.SqlClient#175]
Make a connection to the OOB Adventure Works 2014 database and create this type:
type AdventureWorks = SqlProgrammabilityProvider<connectionString>

When you try and traverse dbo, you can see via intellisense that the table's type is being generated
![image](https://cloud.githubusercontent.com/assets/1394644/11164499/8c83c3ea-8ac0-11e5-8c9c-cf6fa28a8a5d.png)

When you try and traverse any of the other schemas (like Production), no types are getting generated:
![image](https://cloud.githubusercontent.com/assets/1394644/11164504/b740955e-8ac0-11e5-912d-8e6347996c0a.png)

**Comment by dmitry-a-morozov** [comment]
https://msftdbprodsamples.codeplex.com/releases/view/125550
Which one out of these OOB Adventure Works 2014?

I use regular AdventureWorks for testing
https://github.com/fsprojects/FSharp.Data.SqlClient/blob/master/src/SqlClient.Tests/DataTablesTests.fs

**Comment by jamessdixon** [comment]
Adventure Works 2014 Full Database Backup.zip <https://msftdbprodsamples.codeplex.com/downloads/get/880661>

**Comment by dmitry-a-morozov** [comment]
I cannot repro this. 
It would be great of you can help me to replicate incorrect behavior.
I use AdventureWork 2015 as test database.
Those tests include data tables from Production schema.
https://github.com/fsprojects/FSharp.Data.SqlClient/blob/master/src/SqlClient.Tests/DataTablesTests.fs

It must be some permissions/security related issue.
Make sure an user that you use at design time has access to proper namespaces.

The type provider probably can do a better job showing clear error message when a user doesn't have sufficient permissions to read metadata. But this is non-trivial. I'll keep it in mind.

**Comment by jamessdixon** [comment]
can you send me an email to jamessdixon@gmail.com with your ip?
I will add you to my azure firewall rules and then send you the script I ran
Perhaps this is an azure thing?

**Comment by dmitry-a-morozov** [comment]
I have same set of tests passing for sql azure version of AdventureWorks too.
The only difference that I could not find AdventureWorks 2014 for Azure so I use 2012 version.
http://msftdbprodsamples.codeplex.com/releases/view/37304

I'm currently in a office so I'll send you my home ip later this evening.

**Comment by dmitry-a-morozov** [comment]
I think I figured it out.
Try to add reference to Microsoft.SqlServer.Types assembly.

**Comment by jamessdixon** [comment]
I am around tonight if you want to chat…

**Comment by dmitry-a-morozov** [comment]
Let's try. 
Google hangouts?
What time is good for you?

**Comment by jamessdixon** [comment]
Sure

I am here now until 9PM eastern
