### ISSUE TITLE
Support for return values

### ISSUE THREAD

**Issue by Overlord-Zurg** [fsprojects/FSharp.Data.SqlClient#176]
My company's database procedures use return values pervasively. Could they be optionally supported by SqlProgrammabilityProvider?

e.g. a "UseReturnValue" type parameter which changes the return value of an execution from (RecordSet) to a tupled (ReturnValue, RecordSet)

    type Db = SqlProgrammabilityProvider<
        ConnectionStringOrName = DEV_CONN_STRING, 
        UseReturnValue = true>

    type Employee = Db.dbo.employee_get

    let cmd = new Employee()
    let retVal, results = cmd.Execute(employee_id=Some 5)

**Comment by dmitry-a-morozov** [comment]
I'm working on that. How urgent is that?

**Comment by Overlord-Zurg** [comment]
Not urgent. It will likely be at least a year before we would make widespread use of it.

**Comment by dmitry-a-morozov** [comment]
fixed in v1.8
