### ISSUE TITLE
Make pattern matching work for SqlEnumProvider

### ISSUE THREAD

**Issue by panesofglass** [fsprojects/FSharp.Data.SqlClient#177]
When using `SqlEnumProvider` and a single value to generate a module of string values, the generated output does not mark each string value with the `LiteralAttribute`, thereby rendering such generated types useless in pattern match expressions. Please generate the `LiteralAttribute` for those constant values so they can be used in pattern match expressions.

**Comment by dmitry-a-morozov** [comment]
fixed in v1.8

**Comment by panesofglass** [comment]
Thank you!!!
