### ISSUE TITLE
SqlProgrammabilityProvider documentation is incorrect

### ISSUE THREAD

**Issue by jdwalker** [fsprojects/FSharp.Data.SqlClient#180]
In the [configuration document](http://fsprojects.github.io/FSharp.Data.SqlClient/configuration%20and%20input.html), the following is stated:

>SqlProgrammabilityProvider<...> supports connection name syntax as well. It is also possible to pass run-time connection string to database constructor:

```FSharp 

type AdventureWorks2012 = SqlProgrammabilityProvider<connectionString>

open System

let dbRuntime = AdventureWorks2012(runTimeConnStr)

dbRuntime.``Stored Procedures``.``dbo.uspGetWhereUsedProductID``.AsyncExecute(DateTime(2013,1,1), 1) 
|> Async.RunSynchronously
```

However this is incorrect - the provided types and schemas have no constructors. Instead you have to specific it as an  optional parameter/parameter on the stored procedure call itself e.g.

```FSharp 
dbRuntime.``Stored Procedures``.``dbo.uspGetWhereUsedProductID``(connectionString="fgdfg" ,24)
```

**Comment by dmitry-a-morozov** [comment]
fixed
