### ISSUE TITLE
Support SQL IN operator?

### ISSUE THREAD

**Issue by OkayX6** [fsprojects/FSharp.Data.SqlClient#181]
Hi,

I was trying to use this in a command ```SELECT * FROM table WHERE col IN (@ids)```
But it doesn't work as expected.

The **ids** parameters is a string (**col** is of type string), and not an array of strings.
Formating a list of values as ```'A', 'B', 'C'``` doesn't work because if I switch to a column with an integer type, then the parameter for the SQL Command provider becomes a single integer also.

Thanks!

**Comment by dmitry-a-morozov** [comment]
http://stackoverflow.com/questions/26248397/how-to-use-sql-in-statement-in-fsharp-data-sqlclient

**Comment by OkayX6** [comment]
Ok thanks, I did it this way in the end.
Yes, I was spoiled by other ORMs :)...

**Comment by dmitry-a-morozov** [comment]
It's not about ORM. 
T-SQL doesn't have concept of multi-valued parameters. 
Thus TVP.
