### ISSUE TITLE
SqlCommandProvider does not check for missing non-nullable columns on insert

### ISSUE THREAD

**Issue by kbilsted** [fsprojects/FSharp.Data.SqlClient#186]
Using v.1.7.7 of FSharp.Data.SqlClient I was surprised that the type provider does not check for non-null columns. This led to run-time errors when I added columns to my db table where I was expecting compile-time errors. Here is a simple reproduction scenario

**setup db**

```
CREATE TABLE [dbo].Foo (
    [Id]    INT NOT NULL,
    [other] INT NOT NULL,
    PRIMARY KEY CLUSTERED ([Id] ASC)
);
```

**Start server**
shell>  .\SqlLocalDB.exe c kasperdb -s

**F# program**

```
[<Literal>]
let connectionString = @"Data Source=np:\\.\pipe\LOCALDB#EB2932AF\tsql\query;Initial Catalog=master;Integrated Security=True"

type Insert = SqlCommandProvider<"INSERT INTO FOO (ID) VALUES (2)", connectionString>

[<EntryPoint>]
let main argv = 
    use conn = new SqlConnection(connectionString)
    conn.Open()
    use cmd = new Insert(conn)
    cmd.Execute()
```

**Error**
When I run my program i get the error

```
An unhandled exception of type 'System.Data.SqlClient.SqlException' occurred in System.Data.dll

Additional information: Cannot insert the value NULL into column 'other', table 'master.dbo.Foo'; column does not allow nulls. INSERT fails.
```

**Expected errors**

I'm pleased to see the following sql giving compile time errors

```
type Insert = SqlCommandProvider<"SELECT bob FROM dbo.Foo", connectionString>
```

and

```
type Insert = SqlCommandProvider<"INSERT INTO FOO (ID2) VALUES (2)", connectionString>
```

so why am I not getting an error when I forget to insert values into the non-null column `other`

**Comment by smoothdeveloper** [comment]
@kbilsted the type provider relies on sys.sp_describe_undeclared_parameters and sys.sp_describe_first_result_set but is not running further analysis of SQL code.

Also consider that in some circumstances, the statement might be valid (default values, triggers, maybe other things) so it would actually be difficult / exensive to have a compile time check which is working in 100% of the cases.

**Comment by kbilsted** [comment]
Hi @smoothdeveloper 

Thanks for the quick reply - and a great library ;). Why is it a problem to find all non-null non-default columns of an insert?

e.g. use

```
SELECT TABLE_CATALOG AS Database_Name, TABLE_SCHEMA, TABLE_NAME, COLUMN_NAME, IS_NULLABLE, COLUMN_DEFAULT
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_SCHEMA = 'foo'
AND TABLE_NAME = 'bar'
AND IS_NULLABLE = 'NO'
AND COLUMN_DEFAULT IS NOT NULL
```

The trigger argument is a separate can of worms and may already today create problems. Recall, that a before-trigger may completely alter the actual insert that is performed, and hence will not be compatible with the library as it is today.

The "expensive", I guess, is relative to the person and the computer setup. Perhaps performance issues can be resolved with caching values?

**Comment by smoothdeveloper** [comment]
@kbilsted, sorry I'm not one of the maintainers of this great library, but I'm sure you'll get a more thorough answer from them soon, with maybe more positive outcome for your suggestion.

I know it's possible to query the column information, what I meant regarding performance is the number of things the type provider has to check. On projects where lots of those are being declared there is a significant penalty for having extra-checks beside the calls to those procedures I mentioned, it's true that it's not an end-all regarding what you are considering.

This is not the main argument though, I think with the edge-cases, it would be difficult to come with a solution which works 100% of the time, and I think the library tries very hard to provide this.

What about statements which have several inserts, interspersed with other SQL statements? would you expect the library to parse the SQL to figure out if there are inserts to check? What about update statements?

I think my simple answer is that SQL server itself doesn't warn you when you write such statements, I don't see the library evolving toward having it's own custom SQL validation.

**Comment by dmitry-a-morozov** [comment]
@kbilsted 
Primary purpose of the library is to provide static types for input parameters and output result-set.
Thing that you mention falls into category of formal code verification which can be quite tricky. 
Remember sql statement you feed into type provider can be arbitrary complex. For example you can have a logic that will insert different data depending on some condition. Also, as @smoothdeveloper correctly pointed out, some things that can affect end result is out of statement scope completely: triggers, defaults etc. 
That said the library has solution for your particular problem - statically typed data tables
http://fsprojects.github.io/FSharp.Data.SqlClient/data%20modification.html

P.S.
@smoothdeveloper Thank you for providing great initial answer.

**Comment by smoothdeveloper** [comment]
Closing, this would require type checking through parsing the insert statements and validating against database schema.
