### ISSUE TITLE
Using SqlCommandProvider with app.config

### ISSUE THREAD

**Issue by MangelMaxime** [fsprojects/FSharp.Data.SqlClient#187]
Hello guys, I can't find a way to use my app.config settings with SqlCommandProvider.

I tried : 
```fsharp
use cmd = new SqlCommandProvider<"T-SQL/insertTask.sql", "name=SQLHerebris", ConfigFile = @"App.config">()
```

But it's say  :  The type 'FSharp.Data.SqlCommandProvider' doesn't wait any arguments of type but receive 3 argument(s) of type.

I tried to base my code on : [https://github.com/fsprojects/FSharp.Data.SqlClient/blob/b3f2eb3b13de34bbe8fd18820af627d04019662f/src/SqlClient.Tests/Scripts/SqlCommand.fsx#L24](https://github.com/fsprojects/FSharp.Data.SqlClient/blob/b3f2eb3b13de34bbe8fd18820af627d04019662f/src/SqlClient.Tests/Scripts/SqlCommand.fsx#L24)

Any idea ?

**Comment by dmitry-a-morozov** [comment]
Can you try inline T-SQL and see of you get the same error? It can be *.sql file related problem.

**Comment by MangelMaxime** [comment]
Hum, sound strange. 
I was try the previous code at work and got the errors.

And tonigth I just tried it at home (another computher) and it's working.

Not sure what is the difference. I will try to save the current version of the code and test it exactly as it tomorrow.

**Comment by dmitry-a-morozov** [comment]
did you use same version of the library?

**Comment by MangelMaxime** [comment]
@dmitry-a-morozov Seems to work now.

I used Azure and not my local sql server and it work as it.
I think, I have some configuration problems on the local sql server so nothing to do with the library probably.

Sorry and thanks for your time.
