### ISSUE TITLE
continuous deployment

### ISSUE THREAD

**Issue by jackfoxy** [fsprojects/FSharp.Data.SqlClient#189]
missing pieces like test database

**Comment by isaacabraham** [comment]
hmmm? I'm using the TP in a CI environment along with FAKE - works very well.

**Comment by jackfoxy** [comment]
@isaacabraham  this was a reminder to @dmitry-a-morozov about something we discussed...

I can't recall exactly, but these were the words he wanted me to use. I think he wants to build out the CI environment further.

**Comment by dmitry-a-morozov** [comment]
@isaacabraham Currently the project itself completely lacks proper CI setup with unit tests. It needs to be fixed.

**Comment by isaacabraham** [comment]
Oh - sorry. I thought this was about a CI story for when using the TP :-)

**Comment by smoothdeveloper** [comment]
Closing old discussion.
