### ISSUE TITLE
Statically typed data table ctor fails when *.config file is missing at runtime

### ISSUE THREAD

**Issue by ntr** [fsprojects/FSharp.Data.SqlClient#197]
Currently if SqlClient is using connection string from app.config at design time it also expects this connection string available in app.config during the runtime. 
When I am calling data table constructor and app.config connection string is not provided I am getting exception:

> System.Collections.Generic.KeyNotFoundException: Cannot find name MyConnection in <connectionStrings> section of config file.
>    at FSharp.Data.SqlClient.Configuration.GetConnectionStringAtRunTime(String name) in C:\Users\mitekm\Documents\GitHub\FSharp.Data.SqlClient\src\SqlClient\Configuration.fs:line 90

**Comment by dmitry-a-morozov** [comment]
Fixed in v1.8.2

**Comment by dmitry-a-morozov** [comment]
Fixed in v1.8.2
