### ISSUE TITLE
Logo upgrade to be consistent with other popular F# OSS projects

### ISSUE THREAD

**Issue by dmitry-a-morozov** [fsprojects/FSharp.Data.SqlClient#202]
Upgrade logo to rectangular shape same as 
http://bluemountaincapital.github.io/FSharpRProvider/images/logo.png
or
http://bluemountaincapital.github.io/Deedle/images/logo.png

1. F# logo goes to upper-left
2. Current background color needs to be preserved
3. T-SQL barrel goes to bottom-right

Current logo location:
https://github.com/fsprojects/FSharp.Data.SqlClient/blob/master/docs/files/img/logo.png

**Comment by sergey-tihon** [comment]
Something like this?
![image](https://cloud.githubusercontent.com/assets/1197905/14101907/36363040-f5a0-11e5-887c-ea98b01422b5.png)

**Comment by dmitry-a-morozov** [comment]
Yep. Looks good. Thank you
