### ISSUE TITLE
Support typed datatable result for SqlCommandProvider

### ISSUE THREAD

**Issue by smoothdeveloper** [fsprojects/FSharp.Data.SqlClient#213]
In UI context, it is often useful to load data in a DataTable.

A typed DataTable could be generated for each instanciation of SqlCommandProvider.

**Comment by dmitry-a-morozov** [comment]
ResultType.DataTable

**Comment by smoothdeveloper** [comment]
Thanks I was unaware of this.

I guess it would really make sense to not have to declare several queries / not have as strong correlation between the SQL and how the result is used.

**Comment by dmitry-a-morozov** [comment]
Use
```FSharp
[<Literal>]
let myQuery = "SELECT 42"

do
    //records
    use cmd = new SqlCommandProvider<myQuery, conn>()

do
    //data table
    use cmd = new SqlCommandProvider<myQuery, conn, DataType.DataTable>()
```

**Comment by dmitry-a-morozov** [comment]
Also these statically typed DataTables generated by SqlCommandProvider have same support for Update/BulkCopy as direct tables.
http://fsprojects.github.io/FSharp.Data.SqlClient/data%20modification.html

**Comment by smoothdeveloper** [comment]
Do you think it is doable to expose separate method? The underlying infrastructure to support various types is there so I could make a contribution if you think it is worth a shot.

**Comment by dmitry-a-morozov** [comment]
I think declaring 2 types is not too bad.

**Comment by smoothdeveloper** [comment]
I'm not sure adding type provider parameters is the best way to handle those, we can still support the existing one, but I think having a `SqlCommandProvider` enabling to get a datareader, tuples, records and a datatable in separate methods would make a lot more sense and don't constrain the evolution of the type providers (changing input parameters has more impact than exposing new methods/additional types).
