### ISSUE TITLE
when using ResultType = ResultType.DataTable, rows properties don't have a setter

### ISSUE THREAD

**Issue by smoothdeveloper** [fsprojects/FSharp.Data.SqlClient#215]
```fsharp
type MyCommand = SqlCommandProvider< ..., ResultType = ResultType.DataTable>

let data = MyCommand().Execute()

for row in data.Rows do
  row.value <- something
```

this gives `Property 'value' cannot be set.`

I'd like to be able to use it for mutation as well

**Comment by dmitry-a-morozov** [comment]
Of course column values are mutable in most common case. 
Is it computed column?

**Comment by smoothdeveloper** [comment]
You are right, this is what I have in the SQL select statement:
```sql
, cast(null as float) value -- populated in code
```

Am I going to be forced to use `WITH RESULT SETS` which is kind of painful to maintain in my queries (and I need to hack the sql string since I support SQL 2005/2008).

**Comment by smoothdeveloper** [comment]
Would it be OK to expose an override parameter:

`MakeAllDataColumnsWriteable : bool` (or better name if you have one) to workaround this behaviour?

Passing `true` to this parameter is only valid if `ResultType.DataTable` is chosen.

**Comment by dmitry-a-morozov** [comment]
Use 
```FSharp
row.["MyColumn"] <- value 
```
syntax to work around type system

**Comment by smoothdeveloper** [comment]
@dmitry-a-morozov yes thanks I'm using this.

I was hopping to remove that in future because if possible, I like to erase all late binding / unchecked type from the F# and leave it only to C# client consuming the type.

We could have `.ExecuteAsWriteableDataTable`, `.ExecuteAsDataTable`, `.ExecuteAsDataReader`, `.ExecuteAsTupleSequence`, `.ExecuteAsRecordSequence` exposed instead of asking for disjoint ResultType.

**Comment by dmitry-a-morozov** [comment]
It feels like you're asking type system "lie to me" :)
I understand that you deal with SQL Server 2005/2008 but I'm hesitant to add feature to address corner case on database engine version that is not officially supported by the type provider. 

`.ExecuteAsWriteableDataTable`, `.ExecuteAsDataTable`, `.ExecuteAsDataReader`, `.ExecuteAsTupleSequence`, `.ExecuteAsRecordSequence` are look like un-typed raw ADO.NET command. Equipped with input/output type info we can do much better job and keep it simple. 

I'm proud of design where users can just dot into command instance and use `Execute/AsyncExecute` with need to second guess which method they suppose to call. 
It's bad enough I had to add `ExecuteSingle`/`AsyncExcuteSingle` for routines.

To me there is a clear win that single line of type declaration like:
```FSharp
type Get42  = SqlCommandProvider<"SELECT 42", connStr, ResultType.DataTable>
```
has all information required to know input/output types without relying on techniques like method overloading.

**Comment by smoothdeveloper** [comment]
@dmitry-a-morozov I understand your standpoint on the methods, I'll workaround by generating several command types (I have a generator to create those based on a hierarchy of folders containing .sql files) with same sql literal.

Regarding making the property setter available disregarding origin of the column:

When user gets the data in the UI or logic code, in a DataTable, the most likely usecase is that it is going to be edited, and it can actually be edited disregarding the erased type (by making column writeable and using the indexed property with a string).

With the lack of `nameof` operator, I'm going to need to resort to hack with quotation to get the actual name of the column:

````fsharp
let row : Command.Table.Row = myRow
row.[ getName <@@row.ColumnName@@> ] <- myValue
```

implementing getName will be succeptible to implementation change in the provider, and the other solution I have right now is to rely on string.

The other work around would be if you allow me to implement the feature where the data columns are exposed on `.Table.Columns.<columnname>` but I'm unsure how easy it will be to implement (but I'm willing to give it a shot if you like this feature).

**Comment by dmitry-a-morozov** [comment]
Similar capability already exists on statically typed tables generated by SqlProgrammabilityProvider
https://github.com/fsprojects/FSharp.Data.SqlClient/blob/master/src/SqlClient.Tests/DataTablesTests.fs#L113
implementation
https://github.com/fsprojects/FSharp.Data.SqlClient/blob/master/src/SqlClient/SqlClientProvider.fs#L479 

of course difference that columns available on instance of table. 
but I think you can work with that

**Comment by smoothdeveloper** [comment]
Cool, I'll work on this soon. Thanks for the pointers.

**Comment by smoothdeveloper** [comment]
I'm thinking they should go under `table.Columns.here` because of various naming conventions that can be observed in SQL (using snake_case mostly if done the way it is seen in SqlProgrammabilityProvider, it means `table.snake_caseColumn` instead of `table.Columns.snake_case`).

What do you think?

**Comment by dmitry-a-morozov** [comment]
`table.Columns.here` is nicer but much harder to implement. I wondered if it was worth an effort. 
But you can try.

**Comment by smoothdeveloper** [comment]
@dmitry-a-morozov do you happen to know how specifying `with resultsets` would solve the lack of setter for computed column?

I'm not sure this can be achieved in the sql itself.

**Comment by smoothdeveloper** [comment]
@dmitry-a-morozov I'm able to put those under `table.Columns` and it is not too much trouble.

I'm now considering adding this to each of the DataColumn if you don't mind:

```fsharp
member this.GetValue (row :DataRowType) : ColumnType
member this.SetValue (row: DataRowType) (value: ColumnType) : unit
```

That solves the issue with handling `DBNull` instead of option and provide some type checked guarantees when getting / setting value (can't set with int if column is bool etc.) to replace direct and untyped usages 
```fsharp
let value : obj = row.[table.Columns.my_column]  // obj is sad
row.[table.Columns.my_column] <- "not the correct type"
```

I hope that's ok.

I'd like to complete this work based on the other PR because the code is related, can you give a shot at merging this to master?

**Comment by dmitry-a-morozov** [comment]
Is type of `table.Columns` `DataColumnCollection` https://msdn.microsoft.com/en-us/library/system.data.datacolumncollection.aspx?
I need some time to review your PR. 
So don't rush into anything.
Also, after merge some refactoring is required. It has nothing to do with PR but with how code is currently structured.  But it's related to the PR.

**Comment by smoothdeveloper** [comment]
@dmitry-a-morozov 

> Is type of table.Columns DataColumnCollection https://msdn.microsoft.com/en-us/library/system.data.datacolumncollection.aspx?

Yes, but with added properties returning the correct `DataColumn`, it works well.

> Also, after merge some refactoring is required. It has nothing to do with PR but with how code is currently structured. But it's related to the PR.

We should use same methods for `SqlCommand` and `SqlClient` to generate the tables, that will shave lot of duplication.

**Comment by smoothdeveloper** [comment]
I'm also considering adding literals to help with pattern matching (very useful in UI for event handlers):

```fsharp
type MyCommand = SqlCommandProvider<"...", ..,  ResultType.DataTable>

match column with
| MyCommand.Table.ColumnNames.column_a -> ...
```

We could do this for ResultType.Records as well, in which case it should be (for both) `MyCommand.ColumnNames`.

**Comment by dmitry-a-morozov** [comment]
Active patterns will do just fine for that

**Comment by dmitry-a-morozov** [comment]
Send PR that adds columns on Columns collection. 
Don't forget re-base to master's head

**Comment by dmitry-a-morozov** [comment]
And open separate issue only for that. I'm closing this one.

**Comment by smoothdeveloper** [comment]
@dmitry-a-morozov Thanks for all feedback.

I've implemented the new feature: #219, forwarding discussion there.

**Comment by dmitry-a-morozov** [comment]
@smoothdeveloper Can you explain why you have to have those fake read/write computed fields on a data row  instance? Data binding?

**Comment by smoothdeveloper** [comment]
@dmitry-a-morozov I'm displaying data in UI, but some fields can't efficiently be computed in the query, they'd get populated in the data access / business layer but still part of the typed table.

This is a better solution than taking the DataTable and adding a column outside of the query, which causes issues with the Add/NewRow & probably other things.

**Comment by dmitry-a-morozov** [comment]
Why don't you have something like (psudo code below)
```FSharp
type Item = {
    Row: MyTable.Table.Row
    mutable ComputedField1: int
    ...
}
```

**Comment by smoothdeveloper** [comment]
Binding this in the UI is a pain compared to binding a dataview.

**Comment by dmitry-a-morozov** [comment]
Do you use dynamic columns binding or specify names explicitly for individual columns?

**Comment by smoothdeveloper** [comment]
my sql query has 

```sql
cast(null as float) column_name
```

I don't do anything for the binding

```csharp
control.DataSource = theTable; // or a DataView
```

Am I understanding your question right?

**Comment by dmitry-a-morozov** [comment]
Got it. So your code dynamic at nature to some extent anyway.
I mead nothing stops you from writing
`cast(null as float) column_name`
or
`cast(null as decimal) column_name`
or
`cast(null as decimal) column42`
anything. 

So how's that better than 
```FSharp
let computeColumn = new DataColumn("column_name", DbType.Float)
t.Columns.Add computeColumn
t.Rows.[computeColumn].Value <- 42.
```

**Comment by smoothdeveloper** [comment]
My query is static, it is in a .sql file that the TP is loading and turning into generated type, so the column is always a float.

Having the setter:

```fsharp
member __.SetValue(row: MyCommand.Table.Row, value int)
```

provides more type safety for setting and reading the value, without it (but still my column in the sql)

```fsharp
let table : MyCommand.Table = ...
let row = table.Rows.[0]
row.[table.Columns.my_int_column] <- "not an int"
let something : obj = row.[table.Columns.my_int_column] // get an obj back, need to figure out what it could be
```

Compared to

```fsharp
let table : MyCommand.Table = ...
let row = table.Rows.[0]
table.Columns.my_int_column.SetValue(row, "not an int") // compile error
```

While I'm in F# code, I try to avoid as much as possible using System.Data.DataRow members (which allow me to do stuff which will fail at runtime), but rely on the type safety that I can leverage from the TP.

**Comment by dmitry-a-morozov** [comment]
It seems like you try to solve UI tier problems via data access library.
Let's assume for a moment that I'm fine with `GetValue`/`SetValue` on columns.
But I still don't think it's reasonable to generate `SetValue` for read-only column.
So it won't solve your problem anyway.

**Comment by smoothdeveloper** [comment]
We can leave UI and tiers out of consideration, I mostly want to get a typed datatable from the type provider based on the shape of my query, and have tools to edit the contents of it in type safe manner.

Without `GetValue`/`SetValue` I cannot edit the data un my F# code in a type safe manner.

I'm fine to have to resort to bare `DataRow[DataColumn]` setter but dealing with `Nullable`/`Option`/`DBNull` in weird ways and not being sure the type is consistent to what I expect reduces the guarantees that my code will work at runtime.

I think those added `GetValue`/`SetValue` are not too much in the way of most users (who use the properties on the `DataRow`), they have to go out of their way in cases they want the type safety and edit their data which makes it explicit that something special is happening with the data.

**Comment by dmitry-a-morozov** [comment]
Can you add read/write column to database for computed property?

**Comment by smoothdeveloper** [comment]
the data is in a report tables which tend to be several gigs large so I'll refrain to implement this workaround and keep a bit of type unsafety in the code :smile:
