### ISSUE TITLE
use paket instead of several packages.config files

### ISSUE THREAD

**Issue by smoothdeveloper** [fsprojects/FSharp.Data.SqlClient#216]
This project is still relying on tedious low level nuget dependencies (don't handle transitive dependencies properly, forces updating project files when updating a version of a dependency, no consistency check among all the packages.config files).

I could contribute migration to paket if maintainers are OK, I can also do the same in the separate V2 branch.

Would you take contribution to migrate to paket?

**Comment by dmitry-a-morozov** [comment]
Do you mean output package dependencies or TP project itself?

**Comment by smoothdeveloper** [comment]
@dmitry-a-morozov I mean handling of dependencies, but not how the FSharp.Data.SqlClient nuget package is created / published.

At least as a first step.

**Comment by dmitry-a-morozov** [comment]
Can you give an example of dependency?

**Comment by smoothdeveloper** [comment]
@dmitry-a-morozov 

instead of having those in scattered packages.config files, we can make a single `packet.dependencies` and organize groups (one for testing, one for samples, etc.)

* FSharp.TypeProviders.StarterPack
* FSharp.Configuration
* Newtonsoft.Json
* xunit
* xunit.runner.visualstudio
* FSharp.Data.SqlClient (I think this one in the WpfDataBinding sample should just bind to the compiled version, but we can still put it under a "sample" dependency group in paket)
* Microsoft.AspNet.WebApi.Client
* Microsoft.AspNet.WebApi.Core
* Microsoft.AspNet.WebApi.WebHost
* Microsoft.AspNet.WebApi

**Comment by dmitry-a-morozov** [comment]
But these are test/sample project dependencies except FSharp.TypeProviders.StarterPack
I don't think it makes sense to use paket to handle one FSharp.TypeProviders.StarterPack dependency

**Comment by smoothdeveloper** [comment]
xunit, FSharp.Configuration, FSharp.TypeProviders.StarterPack and maybe few others are dependencies for building the repository not related to the samples.

We can leave the samples as they are but still gain ease of maintenance using paket for the more important dependencies.

**Comment by dmitry-a-morozov** [comment]
Although paket is great tool but it will be overkill for this project.
I know that you deal with particular challenge of recompiling this project.
I don't know exactly how you do it but you can run paket convert every time you pull the latest version.

**Comment by smoothdeveloper** [comment]
Matters of perspective, I guess, for me maintaining packages.config (nothing checks they are consistent across the repository) and updating .proj files to match with version number on dependency update is overkill and unnecessary work.

I've done a few migrations and it seems low-risk, I only see easier maintenance compared to bare-bone usage of nuget.

The aim would be only the projects but not the sample projects.

**Comment by smoothdeveloper** [comment]
Trying to use nuget restore packages from Visual Studio in the solution and having it mess the test project with FSharp.Core binding redirect issues... Another reason why paket should be used.

**Comment by charlesroddie** [comment]
> This project is still relying on tedious low level nuget dependencies (don't handle transitive dependencies properly, forces updating project files when updating a version of a dependency, no consistency check among all the packages.config files).

I think the nuget issues are fixed now and packages.config doesn't exist any more. So can we move back to nuget?

**Comment by charlesroddie** [comment]
Relevant discussion from slack
![image](https://user-images.githubusercontent.com/19760720/194124300-0f8d8653-f2a5-4778-8939-d789bb5996d2.png)

**Comment by smoothdeveloper** [comment]
@charlesroddie, have you run the build.cmd script?

I'm on a machine without VS 2019, it seems VS 2022 dropped support for .NET 4.0 targeting pack, I think we need to update some of the .NET 4.0 remaining projects to make build.cmd work with VS 2022 environment only.

I don't think paket is really an issue here, it helps keep the dependencies fixed on same version across the repository.

**Comment by charlesroddie** [comment]
I didn't try running anything. When I deleted files that seemed obsolete or paket-related it did build: https://github.com/charlesroddie/FSharp.Data.SqlClient/pull/1
