### ISSUE TITLE
reduce size of generated code

### ISSUE THREAD

**Issue by smoothdeveloper** [fsprojects/FSharp.Data.SqlClient#223]
I was looking at the il generated (in C# via ilspy) for the unit tests and figured out that there was scope for reducing a lot the size of generated code if we introduce helper methods and call those instead of having large quotations.

The current connection checking is quite verbose, I'm sure there are other areas that could be slimmed a bit as well.

before

``` fsharp
<@@
... lot of code
@@>
```

after

``` fsharp

module Helper
   let HelpMe () =
       ... lot of code
<@@
Helper.HelpMe()
@@>
```

**Comment by dmitry-a-morozov** [comment]
Can you be more specific?
Maybe send github links? 
I thought most of connection checking happens here
https://github.com/fsprojects/FSharp.Data.SqlClient/blob/master/src/SqlClient/ISqlCommand.fs#L61

**Comment by smoothdeveloper** [comment]
I was looking at the highlighted code

![image](https://cloud.githubusercontent.com/assets/87944/15166277/90dc397e-171d-11e6-8ebc-4f520872bdb5.png)

I assume making this quotation call a static helper function would help reducing the highlighted code:

https://github.com/fsprojects/FSharp.Data.SqlClient/blob/5773dd05121afd5cea519687d85efc23a42282ee/src/SqlClient/DesignTime.fs#L533

**Comment by dmitry-a-morozov** [comment]
I can wrap this into function
https://github.com/fsprojects/FSharp.Data.SqlClient/blob/5773dd05121afd5cea519687d85efc23a42282ee/src/SqlClient/Configuration.fs#L72
which can save a bit not much
but everything else - I don't know. 
It basically bridges type unsafe world of .NET like signatures to type safe F#.

**Comment by smoothdeveloper** [comment]
Closing, I think this is minor concern for now. Discussion can continue in this thread.
