### ISSUE TITLE
Table Valued Parameters and ToDataTable conversion function

### ISSUE THREAD

**Issue by smoothdeveloper** [fsprojects/FSharp.Data.SqlClient#224]
I intend to use Table Valued Parameters but unfortunately I'll use them with stored procedures that rely on dynamic SQL, I'd still like to benefit from the types being available to me via `SqlProgrammabilityProvider`.

Would it be ok to add a `ToDataTable` static function on the TVP UDDT taking a seq of the UDDT item?

**Comment by dmitry-a-morozov** [comment]
I think I have a better idea. Give me some time to think it through.

**Comment by smoothdeveloper** [comment]
@dmitry-a-morozov do you have a vague idea what you'd prefer?

As far as I can see, the plain ADO.NET approach is to use a DataTable or other more obscure types, I think it would be a great feature to have that option, even if we figure out a better alternative (which works with seq of UDDT) it will be simple to migrate code to more efficient / elegant solution later.

**Comment by dmitry-a-morozov** [comment]
https://github.com/fsprojects/FSharp.Data.SqlClient/commit/75fdcfe363f0c7101142d95388e7ad22a83d0943
This is coming for you. 
This test case
https://github.com/fsprojects/FSharp.Data.SqlClient/blob/75fdcfe363f0c7101142d95388e7ad22a83d0943/src/SqlClient.Tests/TVPTests.fs#L102

So only minor drawback is that you need to cast it to seq<SqlDataRecord>

Implementation heavily complicated by fact that Mono runtime doesn't have ```SqlDataRecord type. But I want keep Mono compatibility for now.

**Comment by smoothdeveloper** [comment]
Thanks @dmitry-a-morozov, it seems it will be easy to wrap in a custom function to conceal the explicit cast to a single place!

The solution looks great.

**Comment by dmitry-a-morozov** [comment]
@smoothdeveloper  Do you want me to do nuget release or you build from sources anyway?

**Comment by smoothdeveloper** [comment]
@dmitry-a-morozov  I'll be updating via nuget whenever it is available but there is no hurry at the moment.

Thanks!

**Comment by smoothdeveloper** [comment]
Closing this issue as there is now way to reuse TVP types with raw commands. Thanks!
