### ISSUE TITLE
support custom Date class

### ISSUE THREAD

**Issue by dmitry-a-morozov** [fsprojects/FSharp.Data.SqlClient#227]
ADO.NET is being known for NOT SUPPORTING Sql Server Date datatype 
Allow to inject custom implementation of Date type like
```FSharp 
type Date = { Year: int; Month: int; Day: int }
```

**Comment by smoothdeveloper** [comment]
@dmitry-a-morozov I remember there is a Date class coming in next .net framework. Just to keep in mind.

**Comment by dmitry-a-morozov** [comment]
@smoothdeveloper Really? Can you send me a reference?

**Comment by smoothdeveloper** [comment]
It is in corefxlab (so not officially part of dotnet core, at least right now)

https://github.com/dotnet/corefxlab/blob/9b19008b8782f668d45eb05ba155ab30a85f0c6b/src/System.Time/System/Date.cs
