### ISSUE TITLE
Stored procedure or command involving dynamic SQL return int.

### ISSUE THREAD

**Issue by smoothdeveloper** [fsprojects/FSharp.Data.SqlClient#229]
I have a stored procedure involving dynamic SQL, the return type is currently unhelpful (`int`).

I'd benefit having a .ExecuteReader, right now I need to get a `SqlCommand` and set the parameters manually (I loose all the type checking).

If we can detect procedures relying on dynamic SQL, we should expose the same features as plain ADO.NET but still keep the checking on parameters.

**Comment by dmitry-a-morozov** [comment]
Why can't you use ```EXECUTE WITH RESULT SETS``` for that?
http://sqlmag.com/blog/sql-server-2012-t-sql-glance-execute-result-sets

**Comment by smoothdeveloper** [comment]
@dmitry-a-morozov I can't use `EXECUTE WITH RESULT SETS` because runtime server I support doesn't support that feature; I have a workaround for this for SqlCommand where I strip that part from the SQL code at runtime but doing this with a stored procedure will be tricky (haven't investigated that).

I'm facing several difficulties for which I have less than optimal workaround (losing strong typing and need to perform some hoops).

* can't use `EXECUTE WITH RESULT SETS` in stored procedure (in my case, I need stored procedure because i'm using TVP, that only works with stored procedure)
* can't transform TVP values from SQL programmability provider to a DataTable I can pass to my plain ADO.NET command (I need to use that plain command because I don't have a way to use the `.ExecuteReader` I'm proposing we could add in case I was describing)
* can't instantiate a typed result datatable based on another command (I have to execute that other command with parameters which bring 0 results to instantiate a table that I can then load with the data reader from my plain ADO.NET command)

They are all related to my use case where I introduced the stored procedure with dynamic SQL, to address point 2 could we discuss #224, to address point 3 could we discuss #228?

Thanks

**Comment by dmitry-a-morozov** [comment]
How about something like:
```sql
CREATE PROCEDURE [dbo].[Test](@personID int, @firstName nvarchar(50), @lastName nvarchar(50), @tsql nvarchar(max) = '')
AS 
BEGIN

	DECLARE @result TABLE 
	(
		PersonID int NOT NULL, 
		FirstName nvarchar(50) NULL, 
		LastName nvarchar(50) NULL
	)

	IF @tsql <> ''
		INSERT INTO @result
		EXEC(@tsql)
	ELSE 
		INSERT INTO @result
		VALUES (@personID, @firstName, @lastName)

	SELECT * FROM @result
	RETURN;
END;

```

**Comment by smoothdeveloper** [comment]
@dmitry-a-morozov that looks great, I'll give it a try and close the issue or comment back.

Thanks for looking into this!

**Comment by smoothdeveloper** [comment]
Closing this in benefit of #244 and #228 which would help me in this situation.

Thanks for feedback @dmitry-a-morozov
