### ISSUE TITLE
Insert Image With Stored Procs Crops Byte Array

### ISSUE THREAD

**Issue by jon49** [fsprojects/FSharp.Data.SqlClient#231]
### Description

Inserting image crops byte array. When using stored procedure with `SqlProgrammabilityProvider`.

### Repro steps

1. Create a table with an image:

    ```sql
    CREATE TABLE Photo
    (
        PhotoID INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
        img IMAGE NOT NULL
    )
    ```

2. Create the stored procedure:

    ```sql
    USE [DBNAME]
    GO
    /****** Object:  StoredProcedure [dbo].[TestPhoto]    Script Date: 6/15/2016 12:31:21 PM ******/
    SET ANSI_NULLS ON
    GO
    SET QUOTED_IDENTIFIER ON
    GO
    -- =============================================
    -- Author:		Jon Nyman
    -- Create date: 
    -- Description:	Test Photo
    -- =============================================
    ALTER PROCEDURE [dbo].[TestPhoto] 
        -- Add the parameters for the stored procedure here
        @img image
    AS
    BEGIN
        -- SET NOCOUNT ON added to prevent extra result sets from
        -- interfering with SELECT statements.
        SET NOCOUNT ON;
        Declare @id int
        -- Insert statements for procedure here
        INSERT INTO dbo.Photo (img) VALUES (@img)
        set @id = SCOPE_IDENTITY()
        select @id
    END
    ```

3. Connect SqlProgrammabilityProvider:

    ```fsharp
    
    #r @"..\packages\FSharp.Data.2.3.0\lib\net40\FSharp.Data.dll"
    #r @"..\packages\FSharp.Data.SqlClient.1.8.2\lib\net40\FSharp.Data.SqlClient.dll"
    
    open System.IO
    open FSharp.Data
    
    [<Literal>]
    let ConnectionString = "..."

    type Db = SqlProgrammabilityProvider<ConnectionString>
    
    do
        let img = File.ReadAllBytes(Path.Combine(downloadsPath, "APicture.jpg"))
        use cmd = new FieldOpsDb.dbo.TestPhoto(ConnectionString)
        cmd.Execute(img)
        |> printfn "%A"
    ```

### Expected behavior

I expected the full image to be in the database.

### Actual behavior

 Instead only a small portion of it was saved. E.g.,

`0xFFD8FFE000104A464946000101000048`

### Known workarounds

Use `SqlCommandProvider` to directly insert the image.

### Related information 

* Windows 7
* Branch???
* Version: 1.8.2
* SQL 2012
* .NET Framework 4.5.2
* F# Target 4.3.1.0
* VS 2015

**Comment by dmitry-a-morozov** [comment]
Great to see that you took time to create very well defined issue ! 
I will look into it ASAP.

**Comment by dmitry-a-morozov** [comment]
I think the issue caused by out-dated `image` data type.
https://msdn.microsoft.com/en-us/library/ms187993.aspx
Can you switch to `varbinary(max)`?

Run meta-query below to see that max length for `@img` parameter is 16, which is weird. 
```SQL
select TYPE_NAME(system_type_id), name, system_type_id, max_length
from sys.parameters x where x.object_id  = OBJECT_ID('dbo.TestPhoto')
	and name = '@img'
```

**Comment by jon49** [comment]
That worked. Thanks for looking at this problem! I wish I would have figured that out myself and not wasted your time. But it is good to know for others now! Thanks again.

**Comment by dmitry-a-morozov** [comment]
No problem. I'm happy to help.
