### ISSUE TITLE
Expose ContinueUpdateOnError on strongly typed data tables

### ISSUE THREAD

**Issue by isaacabraham** [fsprojects/FSharp.Data.SqlClient#233]
### Description

It is sometimes necessary to perform an insert of records and continue inserting even if one record fails. With the raw DataAdapter you can set the ContinueUpdateOnError property, but this is not exposed by the strongly type data table model. Perhaps adding optional arguments on the Update() call would suffice?

**Comment by dmitry-a-morozov** [comment]
Sure. I will add this option. 
Meanwhile create you own instance of DataAdapter as workaround.

**Comment by isaacabraham** [comment]
Yep, that's exactly what we're doing now - just means you need a data adapter and sqlcommandbuilder, and must manually pass in connection string etc..

**Comment by dsevastianov** [comment]
Released in 1.8.3, closing
