### ISSUE TITLE
SqlProgrammabilityProvider method documentation

### ISSUE THREAD

**Issue by varon** [fsprojects/FSharp.Data.SqlClient#238]
### Description

Using the NuGet package, there seems to be little documentation on generated type providers.

What is the difference between `AcceptChanges()` and `Update()` on a table?

Why does update have an optional SqlConnection parameter? I presume this is for performance, where you'd want to pool connections used by the programmability provider, but what does it actually do if you don't explicitly set this?
### Repro steps

Use SqlProgrammabilityProvider.
Look at Intellisense for table methods.
### Expected behavior

The table methods should provide some basic documentation as to what they do.
So far, the best option is to look through the [tests here](https://github.com/fsprojects/FSharp.Data.SqlClient/blob/master/src/SqlClient.Tests/ProgrammabilityTests.fs).
### Actual behavior

No documentation is available. Online documentation is minimal.
### Known workarounds

None
### Related information
- W10
- NuGet
- Empty DB, attempting to add records to a table.
- .Net 4.5.2
- VS 2015

**Comment by dmitry-a-morozov** [comment]
I know that docs are far from ideal.
I think you're talking about statically typed data tables. 
You can read about it here
http://fsprojects.github.io/FSharp.Data.SqlClient/data%20modification.html.

Statically typed table extend standard ADO.NET data tables.  So method ```AcceptChange``` is inherited. read about it here https://msdn.microsoft.com/en-us/library/system.data.datatable.acceptchanges(v=vs.110).aspx

```Update``` method is extension to default data tables. Basically it's shortcut to using ```SqlDataAdapter```. Specifically ```connection``` allows to provide run-time override connection object. If not specified design time connection string will be used.
