### ISSUE TITLE
More comparisons to the documentation page

### ISSUE THREAD

**Issue by Thorium** [fsprojects/FSharp.Data.SqlClient#242]
The page is out-dated:
http://fsprojects.github.io/FSharp.Data.SqlClient/comparison.html

Instead of this history-based "why we started at first place", I would like to 
have better comparison of different SQL type-provider data access methods.
Dapper comparison can be there still.

I know it's hard to be objective, everyone may have their favourite tools, 
but let's try at least. Each tool has a slightly different ideology so there
is not only one hammer for all. This is my point of view:
### Common for all TypeProviders
- You write just logic code, not POCO-objects and mappings
- If your database changes, your code breaks on compile time
- No SQL-injection vulnerabilities
- Commit to existing transactions so you can mix with other technologies
- You can call stored procedures if needed.
- Supports joins and nested in-queries so you can avoid "n+1 database hits" problems
### FSharp.Data.SqlClient

Good:
- User has control of SQL-clauses
- So you can hit database indexes with complex queries
- SQL-syntax is already familiar for many
- Supports async database operations.
- Use it e.g. for data processing backends
- Open source

Not so good:
- By default supports only Microsoft SQLServer and its SQL.
- Code overhead if you have a large amount of different small operations.
- Doesn't generate domain model for work with C#
### SQLProvider

Good:
- Supports any database (MSSQL, MySQL, Postgre, Oracle, Odbc, ...)
- Changing the database is not actually huge work!
- Makes effective simple SQL. 
- Supports async database operations.
- Use it e.g. for web servers
- User's code stays simple
- Open source

Not so good:
- No Manual control over generated SQL
- FSharp/LINQ query-syntax is a learning curve
- Doesn't generate domain model for work with C#
- Most LINQ-operations supported, but not yet complex group-by scenarios
### SqlDataConnection

Good:
- You can use generated DB-model from C#-projects
- Supports even complex LINQ-operations

Not so good:
- Generates EF-models on background
- Not dynamic
- Doesn't scale to large databases
- FSharp/LINQ query-syntax is a learning curve
- Closed source
- Supports only Microsoft SQLServer

**Comment by dsevastianov** [comment]
Thanks for looking into this, you make a lot of valid points. 
I might argue about some of them though, for example - Doesn't generate domain model for work with C#. We got to this type provider after quite a few projects using ORMs and it is my strong believe that domain OO model cannot be generically generated from relational database. Impedance mismatch is too high, it tends to create more problems than to solve. That's what we reflected on on that page, and that's why we spent so much time trying to build comparison with Dapper.
Does it make sense?

**Comment by Thorium** [comment]
That is fair, and I agree with that topic. ORM generation to C# isn't good idea in general (and I would recommend to avoid C# as default language), but it is still a reason for some people to select some technology.

Right now F# itself has a lot of different data access technologies and people are not sure what to choose. This page comes first when I search Google on "f# data access comparison" and that is why this information should also be included in the page.

**Comment by dsevastianov** [comment]
I see your point, I'll proceed with the change, thanks for your contribution!

**Comment by dsevastianov** [comment]
Released with some minor changes
