### ISSUE TITLE
Feasability of PostgresSql support?

### ISSUE THREAD

**Issue by jackmott** [fsprojects/FSharp.Data.SqlClient#249]
### Description

I know that this TP depends on two stored procs built into SQL Server that provide the necessary meta data. I'm wondering if it would be possible to write similar stored procs for PostgresSql, such that you could use this type provider with it, provided you first apply the stored procs.  I'd be potentially interested in making the effort if it is at all feasible.

**Comment by dsevastianov** [comment]
It might be interesting to look into, I don't know enough about Postgres to judge on feasibility though.

**Comment by ntr** [comment]
Something that can be potentially helpful:
https://www.postgresql.org/docs/current/static/libpq-exec.html#LIBPQ-EXEC-SELECT-INFO

**Comment by smoothdeveloper** [comment]
@ntr, what is still missing is identifying the parameter names and types.

**Comment by ntr** [comment]
@smoothdeveloper, check PQparamtype - it 
> Returns the data type of the indicated statement parameter.

**Comment by smoothdeveloper** [comment]
@ntr, I see and it looks about right. I think best way to experiment with this is to create a small fsx showcasing how it works.

**Comment by johnberzy-bazinga** [comment]
I've taken a brief look at this in the context of the NpgSql driver. It's possible with NpgSql to execute a describe command by passing` CommandBehavior.SchemaOnly`. That should do the trick for output column types. 

For input parameter types, it's possible to executing a prepared statement followed by reading the `parameter_types` column in the `pg_catalog.pg_prepared_statements` table for the newly added record. 

Not sure if these methods are reliable enough to be used for a TP, but might be worthwhile to further investigate.

**Comment by vasily-kirichenko** [comment]
It's implemented as a independent type provider, check out https://github.com/demetrixbio/FSharp.Data.Npgsql
