### ISSUE TITLE
Question on UPDATE

### ISSUE THREAD

**Issue by jackmott** [fsprojects/FSharp.Data.SqlClient#251]
I've got an update query:

```sql
let cmd = DB.CreateCommand<"
            UPDATE Planets 
            SET Name = @Name, DiscoveredBy = @DiscoveredBy           
            WHERE ID=@ID
            ">(runtimeConn)
        
cmd.Execute(Name=planet.Name,
                      DiscoveredBy = //int or null,
                      ID=ID)
         
```
DiscoveredBy expects an int, but that column in the DB can have nulls. Do I have to use SQLCommandProvider and set allparametersoptional?

Is there a way to do this with Statically-typed DataTables? Without making two round trips to the database?

**Comment by smoothdeveloper** [comment]
@jackmott could you check if passing `AllParametersOptional` in static parameters works in that context?

```fsharp
let cmd = DB.CreateCommand<"
            UPDATE Planets 
            SET Name = @Name, DiscoveredBy = @DiscoveredBy           
            WHERE ID=@ID
            ", AllParametersOptional = true>(runtimeConn)
        
cmd.Execute(Name=planet.Name,
                      DiscoveredBy = //int or null,
                      ID=ID)
```

**Comment by smoothdeveloper** [comment]
For batch update, you could look into:

* Table Valued Parameters (TVP) that you have to define in the database and are exposed by the type provider, but you need a stored procedure to use them in SQL side
* Statically-typed DataTable that you can use with dataadapter (for custom SQL) or plain `Update`  calls http://fsprojects.github.io/FSharp.Data.SqlClient/data%20modification.html
* bulk insert to temporary table and perform update with joins

**Comment by smoothdeveloper** [comment]
@jackmott is there anything needed to solve your question?
