### ISSUE TITLE
Add factory method to SqlProgrammabilityProvider 

### ISSUE THREAD

**Issue by Overlord-Zurg** [fsprojects/FSharp.Data.SqlClient#252]
### Description

When creating a type with `SqlCommandProvider<>`, a static `Create` method is created as a wrapper for the constructor (and with the same arguments). No factory method is created for the types generated by `SqlProgrammabilityProvider<>`.

Statically resolved type parameters can refer to static methods, but not non-parameterless constructors, so there is no way to wrap the creation and execution of a `SqlProgrammabilityProvider`-generated type in a single inline function.

**Comment by vasily-kirichenko** [comment]
Implemented via https://github.com/fsprojects/FSharp.Data.SqlClient/pull/253
