### ISSUE TITLE
Cannot call an SP with an output parameter of type timestamp

### ISSUE THREAD

**Issue by kerams** [fsprojects/FSharp.Data.SqlClient#254]
### Description

Code that calls an SP with an output parameter of type `timestamp` using `SqlProgrammabilityProvider` does not compile.

### Repro steps

Please provide the steps required to reproduce the problem

1. Create the SP
```sql
CREATE PROCEDURE [dbo].[proc_STA_snip]
    @t2 timestamp output
AS
BEGIN
    SELECT @t2 = CONVERT(binary(8), GETDATE())
END
```

2. Call the SP
```fsharp
type Sql = SqlProgrammabilityProvider<"server=snip;database=snip;uid=snip;pwd=snip">

use sql = new Sql.dbo.proc_STA_snip("server=snip;database=snip;uid=snip;pwd=snip")
let _, t2 = sql.Execute ()
```

### Expected behavior

Code compiles and `Execute` returns the result set as well as the output parameter.

### Actual behavior

Compilation fails with
```
The type provider 'FSharp.Data.SqlProgrammabilityProvider' reported an error in the context of provided type 'FSharp.Data.SqlProgrammabilityProvider,ConnectionStringOrName="server=snip;database=snip;uid=snip;pwd=snip"+dbo+proc_STA_snip', member 'Execute'. The error: No parameterless constructor defined for this object.
```

### Known workarounds

None.

### Related information 

* SqlClient 1.8.3-beta4
* SQL Server 2012
* .NET Runtime, CoreCLR or Mono Version - .NET 4.6.1

**Comment by smoothdeveloper** [comment]
@kerams, if you like to have a look at this issue, you can start looking at `DesignTime.GetOutputTypes` https://github.com/fsprojects/FSharp.Data.SqlClient/blob/master/src/SqlClient/DesignTime.fs#L239

**Comment by kerams** [comment]
Thanks for the pointer. I have identified the issue and I also seem to have a working fix.

**Comment by kerams** [comment]
I'm getting compilation errors in the test solution on lines like `type AdventureWorks = SqlProgrammabilityProvider<ConnectionStrings.AdventureWorksNamed, UseReturnValue = true>`. Besides that, how is https://github.com/fsprojects/FSharp.Data.SqlClient/blob/master/src/SqlClient.Tests/SpReturnValueTests.fs#L10 even supposed to work? I don't see a parameterless constructor for sprocs...

**Comment by smoothdeveloper** [comment]
@kerams, somehow that file seems to compile fine in my working copy, can you check app.config is pointing to correct connection strings?

The constructor without parameter will use the design time configuration, in this case what is under connectionStrings element in app.config, I think this is now only available for named connection strings.

What is the compile error you are getting?

**Comment by kerams** [comment]
In `SpReturnValueTests.fs`:
```
type AdventureWorks = SqlProgrammabilityProvider<"Data Source=.;Initial Catalog=AdventureWorks2012;Integrated Security=True, UseReturnValue = true">
// The type provider 'FSharp.Data.SqlProgrammabilityProvider' reported an error: Invalid value for key 'integrated security
```

It works when I remove `UseReturnValue = true`, but then it complains about the aforementioned parameterless constructors.

**Comment by kerams** [comment]
Never mind, I was the problem ;). Thanks again, I've submitted the PR.

**Comment by dsevastianov** [comment]
Thank you @kerams, good find.
