### ISSUE TITLE
SqlProgrammabilityProvider ResultType

### ISSUE THREAD

**Issue by davidtme** [fsprojects/FSharp.Data.SqlClient#257]
### Description

The SqlProgrammabilityProvider intellisense lists 

```
ResultType: A value that defines structure of result: Records, Tuples, DataTable, or SqlDataReader.
```

However this is missing as a parameter.

### Related information 

* v1.8.2

**Comment by smoothdeveloper** [comment]
@davidtme thanks for the report, consider contributing a fix at https://github.com/fsprojects/FSharp.Data.SqlClient/blob/master/src/SqlClient/SqlClientProvider.fs#L57

**Comment by davidtme** [comment]
Thanks for the info @smoothdeveloper but I was hoping to use the User-Defined Table Types as records.

**Comment by smoothdeveloper** [comment]
@davidtme, sorry missed your point, maybe you can look at this then: https://github.com/fsprojects/FSharp.Data.SqlClient/blob/master/src/SqlClient/SqlClientProvider.fs#L125

the feature should be doable (applies to all commands generated) and relatively easy to write tests for.

**Comment by davidtme** [comment]
@smoothdeveloper I've had a look and I think it's a bit beyond me at the moment, I've not done any type provider coding yet.

**Comment by smoothdeveloper** [comment]
If you want this to be implemented, could you rename the issue to something more descriptive and consider posting accurate sample of the feature in use?

**Comment by davidtme** [comment]
See https://github.com/fsprojects/FSharp.Data.SqlClient/issues/258

**Comment by smoothdeveloper** [comment]
@davidtme FYI I've opened PR #261 with intent to enable specifying ResultType on SqlProgrammabilityProvider.

I'm looking for input (within scope of what ResultType means in other areas of the library) to get it working for various usecases, if you have a chance to give it a look that would be helpful.
