### ISSUE TITLE
Build.cmd fails on Windows

### ISSUE THREAD

**Issue by ntr** [fsprojects/FSharp.Data.SqlClient#259]
### Description

Build cmd fails to download packages on windows. I am getting lots of errors about missing nuget packages:
>Unable to find version '2.4.1' of package 'FSharp.Formatting'.
Unable to find version '0.0.36' of package 'FSharp.Compiler.Service'.

### Repro steps

Run build.cmd

### Expected behavior

Build runs successfully. 

### Actual behavior

Build fails with missing error packages. 

### Known workarounds

Please provide a description of any known workarounds.

### Related information 

* Operating system
Windows 10
* Branch
Master

**Comment by ntr** [comment]
Turns out some packages are missing from v2 nuget feed.

**Comment by dsevastianov** [comment]
Merged, thanks!
