### ISSUE TITLE
DesignTime: null-reference exception after a short time

### ISSUE THREAD

**Issue by 0x53A** [fsprojects/FSharp.Data.SqlClient#262]
I successfully built my project:
![image](https://cloud.githubusercontent.com/assets/4236651/23173900/fa5302ba-f85a-11e6-9266-962c3cae97a7.png)

after a short period, the first usage of the SqlCommandProvider gets errors at design time (without any code changes).
![image](https://cloud.githubusercontent.com/assets/4236651/23173891/f39048d4-f85a-11e6-9ee8-6e4b93955d17.png)

Subsequent builds also pass.

Intellisense for this one instance fails (e.g. I can't dot into members, but for other instances it still works:

![image](https://cloud.githubusercontent.com/assets/4236651/23174061/7a6fb1fa-f85b-11e6-9022-4baa35c970c4.png)

Here I can't do anything with ``getState``, but ``getCondition`` works as expected.

__Is there any way to get a callstack?__

I have VS2015.3

``<package id="FSharp.Data.SqlClient" version="1.8.2" targetFramework="net461" />``

**Comment by 0x53A** [comment]
I restart of VS fixed the issue for now, but is there a way to get callstacks for such failures?

**Comment by smoothdeveloper** [comment]
@0x53A I believe fsc.exe would only report Exception.Message on such failure, the way to get the callstack would be to catch the exception and make another one with the Message containing the inner exception.ToString().

The other thing worth considering is opening an issue on visualfsharp repository to make that such errors, for any type provider, would print the whole stacktrace.

**Comment by smoothdeveloper** [comment]
I believe this is the location in compiler handling that error:

https://github.com/Microsoft/visualfsharp/blob/a2bb40f7017de0bb43a79823edaf0c9abce431c6/src/fsharp/tainted.fs#L64

**Comment by smoothdeveloper** [comment]
@0x53A without the compiler showing the full stack trace, or debugging the issue with reproducible steps, it is hard to fix this.

I have not seen such error for long time now, it may have been addressed.

One issue I'm seeing nowadays is a failing dictionary lookup, it might be solved in the master branch with recent refactoring around naked usage of dictionary without locks and few other adjustments which took place in retrieving the sql data types information.
