### ISSUE TITLE
Error working with TVP when the table is empty

### ISSUE THREAD

**Issue by rkosafo** [fsprojects/FSharp.Data.SqlClient#266]
### Description

When working with a stored procedure that uses TVP, I encountered a scenario where the table is blank. Executing the command with an empty sequence for the TVP gives the error

    An exception of type 'System.ArgumentException' occurred in System.Data.dll but was not handled in user code

    Additional information: There are no records in the SqlDataRecord enumeration. To send a table-valued parameter with no rows, use a null reference for the value instead.

Executing it with null gives the error

    An exception of type 'System.NotSupportedException' occurred in System.Data.dll but was not handled in user code

    Additional information: DBNull value for parameter '@accounts' is not supported. Table-valued parameters cannot be DBNull.

A post from stackoverflow suggests that where there is no data, the parameter should not be passed at all. Is this a known issue or a bug?

### Repro steps

1. Create stored procedure that uses TVP
2. Run the stored procedure where

### Expected behavior

Command executes without errors

### Actual behavior

Command gives the above errors at runtime

### Known workarounds

Maybe create another instance of the stored procedure that does not require the accounts

### Related information 

* Operating system: Windows 10
* Branch: 1.8.3-beta5
* Database versions and sample databases being used: Sql Server 2014
* .NET Runtime, CoreCLR or Mono Version: net452
* Editing Tools (e.g. Visual Studio Version): Visual Studio 2015
* Lins to F# RFCs or entries on http://fslang.uservoice.com

**Comment by NaomiN** [comment]
I am having the same issue after I switched to SqlDataReader from DataTables.

**Comment by smoothdeveloper** [comment]
I think #289 solves this issue.

**Comment by vasily-kirichenko** [comment]
Yes, it’s fixed in 1.8.4
