### ISSUE TITLE
Target .NET Core 2.0

### ISSUE THREAD

**Issue by panesofglass** [fsprojects/FSharp.Data.SqlClient#270]
### Description

Provide an updated package that supports .NET Core 2.0. This is not yet ready but getting closer. See https://github.com/Microsoft/visualfsharp/issues/3069. I'm happy to help contribute to this. 

Note that support for .NET Core means reverting `SqlEnumProvider` to an erasing provider, or cutting this from the .NET Core version, as generative providers will not be supported. What should be done in this case? As a user of `SqlEnumProvider`, I would prefer that it revert to an erasing provider, at least for the .NET Core target. I'm not sure whether others are using this for generating true enums or not at this time.

Questions:
1. Is anyone using the generated `System.Enum` feature?
2. Would changing this to an erasing provider adversely affect any cross-language use?
3. Anything else not addressed by the first two questions?

**Comment by dsevastianov** [comment]
It sounds feasible, though it would be great if other users of `SqlEnumProvider` chimed in, especially those calling generated types from other .Net languages. Jet.com should be fine with this change. I would rather make this change across the board and not fork for specific target.

**Comment by panesofglass** [comment]
At Tachyus, we use `SqlEnumProvider` to generate something like:

``` fsharp
module Constants =
    [<Literal>]
    let ``Some Value`` = "Some Value"
    [<Literal>]
    let ``Another Value`` = "Another Value"
```

We don't have any use of generating true enumerations, handy as that is. I'm also not aware of any requirements for the `[<Literal>]` attribute, e.g. as values in an attribute, though that is also a very handy feature.

**Comment by dsevastianov** [comment]
I believe @dmitry-a-morozov implemented this mostly for C# compatibility, and I am not aware of any usages of this feature in the wild. I am fine with the switch.

**Comment by samhanes** [comment]
I made an attempt to migrate the project to target netstandard 2.0, but I ran into a brick wall when I realized that `SqlCommandBuilder` isn't yet available.  It looks like it will be added in netstandard 2.1, so I'll give it another shot once that has been released.

**Comment by dsyme** [comment]
I wrote up notes of what it means to move an existing type provider to support both .NET Standard and loading into .NET Core0-based F# tooling https://github.com/fsprojects/FSharp.TypeProviders.SDK#updating-a-type-provider-to-be-suitable-for-use-with-the-net-sdk

However it looks like SqlCommandBuilder and .NET Standard 2.1 will be needed from the above

**Comment by davidtme** [comment]
@samhanes When you migrated the project target netstandard 2.0 did you upgrade ProvidedTypes.fs to the latest [FSharp.TypeProviders.SDK](https://github.com/fsprojects/FSharp.TypeProviders.SDK)? I've hit a few problem and I'm just wondering if you have already solve them.

**Comment by vasily-kirichenko** [comment]
WIP #291, however, it's not going very well so far.

**Comment by panesofglass** [comment]
Looks like #314 will resolve this.

**Comment by vasily-kirichenko** [comment]
Implemented in https://github.com/fsprojects/FSharp.Data.SqlClient/pull/314
