### ISSUE TITLE
SqlProgrammability Provider problem with no parameter function

### ISSUE THREAD

**Issue by jackfoxy** [fsprojects/FSharp.Data.SqlClient#271]
### Description

SqlClient 1.8.1

ProgrammabilityProvider says Record type is missing for dbo function that takes no parameter (), and returns rows of 2 columns, nvarchar and datetime

### Repro steps

see description

### Expected behavior

should compile

### Actual behavior

compile-time record type is missing for dbo.function(), no errors at design time

### Known workarounds

Use command provider instead.

### Related information 

* Operating system

Windows 10

* Branch
* Database versions and sample databases being used

SQL Azure

* .NET Runtime, CoreCLR or Mono Version

.NET4.6.1

* Editing Tools (e.g. Visual Studio Version)

Visual Studio 2015 and 2017

* Lins to F# RFCs or entries on http://fslang.uservoice.com

**Comment by smoothdeveloper** [comment]
@jackfoxy could you share the definition of such function so it can be added to the test suite?

Thanks.

**Comment by jackfoxy** [comment]
@smoothdeveloper 

````
CREATE FUNCTION [dbo].[TestNoParam]()
RETURNS TABLE
AS
RETURN (SELECT N'test' AS col1, GETDATE() AS col2)
````

**Comment by smoothdeveloper** [comment]
@jackfoxy thanks, I've tried adding a test:

```fsharp
    
[<Fact>]
let ``function with no parameters`` () =
    let fn = new AdventureWorks.dbo.TestNoParam(ConnectionStrings.AdventureWorksLiteral)
    let results = fn.Execute()
    for r in results do
        printfn "%A %A" r.col1 r.col2    
```

The test is passing, and I get autocompletion in ionide on the results; I'm not sure what is the issue or if it is still there.

Do you still have the issue as of today?

**Comment by jackfoxy** [comment]
Honestly, I reported this problem after finding it at work and solved my immediate problem by not using the TP. I don't remember where the problem was, so I can't say for sure that it is fixed either...

I just realized, this probably does not adequately test the issue. You need to change the select statement

````SELECT N'test' AS col1, GETDATE() AS col2````

to actually select 2 columns from your test database. That will really test this.
