### ISSUE TITLE
How to split up a query with joins?

### ISSUE THREAD

**Issue by Kurren123** [fsprojects/FSharp.Data.SqlClient#274]
Something like this:
```
SELECT *
FROM Customer
JOIN Order ON Order.CustomerId = Customer.Id
```

Will return the data denormalised. Whats the easiest way to have the results as a list of `Customer` records each containing a list of `Order` records?

**Comment by ntr** [comment]
SqlClient keeps table semantics for returned objects, the easiest way would be take denormalized table and map it to the objects in application code.

**Comment by Kurren123** [comment]
@ntr  Thanks!
