### ISSUE TITLE
Issues with F#4.1 / VS2017

### ISSUE THREAD

**Issue by isaacabraham** [fsprojects/FSharp.Data.SqlClient#275]
I'm not sure if this is still an issue, but as far as I'm aware it is. We have an F#4.0 solution that does not build on VS2017 against the F#4.1 compiler. I believe this is linked to https://github.com/Microsoft/visualfsharp/issues/2399 - essentially it involves some change to the TP to get it to work.

**Comment by wallymathieu** [comment]
Is this why we see for instance: https://github.com/fsprojects/FSharp.Data.SqlClient/pull/280#issuecomment-358683473 ?

**Comment by vasily-kirichenko** [comment]
@isaacabraham is this still an issue?

**Comment by isaacabraham** [comment]
@vasily-kirichenko I'm not sure. If I remember, the problem wasn't actually the compiler itself but a combination of the compiler + newer build tools in VS2017. We sort of worked around it by using the FSharp.Compiler nuget package and never tested again after that.

**Comment by smoothdeveloper** [comment]
@isaacabraham was the problem happening in a working copy which has been built with VS2015 previously (binaries still in obj/bin folders)?

Also, there is a recent fix in visualfsharp repository which might be related: https://github.com/Microsoft/visualfsharp/pull/4920

If you have more information about the issue you faced, please share it back here.

**Comment by isaacabraham** [comment]
I think that this can be closed now.
