### ISSUE TITLE
Question about type provider: Why does this query result in string option and not just string?

### ISSUE THREAD

**Issue by paul-spoon-olo** [fsprojects/FSharp.Data.SqlClient#276]
### Description

When passing a query into SqlCommandProvider that I expect a `string `from, I am instead getting `string option`

### Repro steps

Say you have the following SQL tables:

"Coupon"
- "Coupon_PK" primary key integer not null auto incrementing

"CouponCode"
- "Coupon_FK" foreign key to "Coupon.Coupon_PK" integer not null
- "Code" nvarchar(50) **not null**

And you want to select a list of all Coupon IDs and the alphabetically first Code for each one.

I would write code like the following

    type SingleCodeCoupon = { Id : int; FirstCode : string }

```
    let test =
        tryCatch "test failed: " (fun campaignId ->
            use cmd = new SqlCommandProvider<"SELECT c.Coupon_PK as Id, MIN(cc.Code) as FirstCode
                FROM Coupon c
	                INNER JOIN CouponCode cc ON c.Coupon_PK = cc.Coupon_FK
                GROUP BY c.Coupon_PK", MyConnectionString>(getConnectionString())
            
            cmd.Execute()
                |> Seq.map (fun row ->
                    {
                        Id = row.Id                                      
                        FirstCode = row.FirstCode
                    })
                |> List.ofSeq |> succeed
        )

```

### Expected behavior

`row.FirstCode` maps correctly as a `string`. 

`row.FirstCode` should be a `string` because it's impossible for this column to ever be null. 

The "Code" column within "CouponCode" can't be null, and with an INNER JOIN there will be no row selected at all if there is no corresponding row in the "CouponCode" table in the first place.

If a row is present, `MIN(cc.Code)` can't be null.

### Actual behavior

`SingleCodeCoupon` type fails to be mapped because `row.FirstCode` is a `string option` type rather than a `string` type.

### Known workarounds

I could just assign the value as `Option.orDefault String.Empty row.FirstCode`, but that seems silly since it's impossible for that column to ever be null in the first place.

### Related information 

* Windows 10 
* Using Visual Studio 2017 Professional
* Database is Microsoft SQL Server

**Comment by dmitry-a-morozov** [comment]
Any aggregation function always yields null-able value.
That's how it's defined in T-SQL
If you think carefully in .NET and F# it should be defined also as
```fsharp
val Min: seq<num> -> Option<num>
```
Because when it defined as 
```fsharp
val Min: seq<num> -> num
```
it becomes partial function and can throw exception and input is empty.
Dig into T-SQL if you want deeper understanding.

**Comment by paul-spoon-olo** [comment]
Thanks for the explanation @dmitry-a-morozov I'll go ahead and close this!

**Comment by dmitry-a-morozov** [comment]
I'm glad that my explanation was helpful. 
Maybe to expand a bit see snippet below
```sql
select min(col) from (values (42), (12)) xs(col) --where 0 > 1
```
Uncomment ```where``` clause and you'' still get one row but with NULL-valued column
