### ISSUE TITLE
Add docs for SqlFileProvider

### ISSUE THREAD

**Issue by vasily-kirichenko** [fsprojects/FSharp.Data.SqlClient#298]

**Comment by smoothdeveloper** [comment]
There is a mention in release notes:

https://github.com/fsprojects/FSharp.Data.SqlClient/blob/7c311d19c4525b45756c394e01de1c00365271e3/RELEASE_NOTES.md#184---may-12-2018

The documentation shows usage and explain the advantages of having separate .sql files:

https://github.com/fsprojects/FSharp.Data.SqlClient/blob/15f77e8ebe44e5617c511d50a20a5227b59a81fd/docs/content/configuration%20and%20Input.fsx#L108

The documentation is actually quite good even if it feels that things are mostly appended.

**Comment by cmeeren** [comment]
I can't find any mention if SqlFile in the docs: https://fsprojects.github.io/FSharp.Data.SqlClient/configuration%20and%20input.html

**Comment by smoothdeveloper** [comment]
@cmeeren there is a mention of SqlFile in a sample on that page, if you'd like more, please submit a PR against the documetation.
