### ISSUE TITLE
Hard to figure out piece of code related to command constructor and static CreateCommand method.

### ISSUE THREAD

**Issue by smoothdeveloper** [fsprojects/FSharp.Data.SqlClient#304]
@dmitry-a-morozov if you have recollection about this:

https://github.com/fsprojects/FSharp.Data.SqlClient/commit/a78b50996104cc91326831bb397183e87939c435#diff-2adb885a1f35811d67432b83ef10e6bcR570

Could you explain the assert here and special addition of provided method to rootType while we don't seem to add other relevant overloads here?

The usage of `CreateCommand` seems to be restricted to only one overload and I'd like to fix this, as well as adding other constructor option.

Thanks for your help!

**Comment by dmitry-a-morozov** [comment]
- The code is confusing that why I put assert in. It's more to explain code rather than verify.
`assert (ctorsAndFactories.Length = 4)`
means it's 2 method factories + 2 constructors 
-  There is only one overload of `CreateCommand` because statically parametrized TP methods do not allow overloads. I'll let you guys to figure out solution to that. 
- `Create` methods were necessary because intellisense didn't work. I know that vasily-kirichenko recently fixed that.

Hopefully it helps.

**Comment by smoothdeveloper** [comment]
@dmitry-a-morozov thanks!

> assert (ctorsAndFactories.Length = 4)

is it worth to change the return type to something custom to surface that information proper? I'll happily take a look at it once I got my head around it.

> because statically parametrized TP methods do not allow overloads.

Thanks I wasn't aware, the solution for that problem is simple, if overloads are not allowed, don't use them :) I'll come up with a set of method names.

Yes @vasily-kirichenko fixed some aspects of intellisense, I haven't tried it yet but it should help.

**Comment by dmitry-a-morozov** [comment]
> is it worth to change the return type to something custom to surface that information proper? I'll happily take a look at it once I got my head around it.

Do you mean to replace array of `ProvidedMethod` with more structured type?

**Comment by smoothdeveloper** [comment]
I mean group the separate ProvidedMethod and ProvidedConstructors in a record so we can explicitly pick the one we are interested in at other places in the code.

**Comment by smoothdeveloper** [comment]
Right now it is an array and the caller needs to know which method is which based on index, this is a bit brittle moving forward.

**Comment by dmitry-a-morozov** [comment]
I don't mind. It's your decision to make.

**Comment by smoothdeveloper** [comment]
Ok thanks again for helping out, I'll close and try to figure out if I can make it more explicit in future change.
