### ISSUE TITLE
SqlCommandProvider type provider constructor exception when using dotnet CLI

### ISSUE THREAD

**Issue by panesofglass** [fsprojects/FSharp.Data.SqlClient#307]
### Description

After updating fsproj files to the new format and targeting `net461`, `dotnet build *.fsproj` fails with the following error:

```
error FS3053 : The type provider 'FSharp.Data.SqlCommandProvider' reported an error : The type provider constructor has thrown an exception: Exception has been thrown by the target of an invocation. [*.fsproj]
FSC : warning FS3005: Referenced assembly 'C:\Users\ryan\.nuget\packages\fsharp.data.sqlclient\1.8.2\lib\net40\FSharp.Data.SqlClient.dll' has assembly level attribute 'Microsoft.FSharp.Core.CompilerServices.TypeProviderAssemblyAttribute' but no public type provider classes were found [*.fsproj]
```

### Repro steps

1. Update fsproj from old format to new format, targeting `net461`.

2. Attempt to build the project with the `dotnet build` command.

### Expected behavior

Successful build.

### Actual behavior

```
error FS3053 : The type provider 'FSharp.Data.SqlCommandProvider' reported an error : The type provider constructor has thrown an exception: Exception has been thrown by the target of an invocation. [*.fsproj]
FSC : warning FS3005: Referenced assembly 'C:\Users\ryan\.nuget\packages\fsharp.data.sqlclient\1.8.2\lib\net40\FSharp.Data.SqlClient.dll' has assembly level attribute 'Microsoft.FSharp.Core.CompilerServices.TypeProviderAssemblyAttribute' but no public type provider classes were found [*.fsproj]
```

### Known workarounds

Build with `MSBuild.exe` rather than the `dotnet` cli.

### Related information 

* Operating system
* Branch
* Database versions and sample databases being used
* .NET Runtime, CoreCLR or Mono Version
* Editing Tools (e.g. Visual Studio Version)
* Lins to F# RFCs or entries on http://fslang.uservoice.com

**Comment by panesofglass** [comment]
Work around is to use msbuild rather than the dotnet cli.

**Comment by samhanes** [comment]
@panesofglass Is this resolved in version 2.0.1?

**Comment by panesofglass** [comment]
Looks like this is fixed! Thanks!

**Comment by panesofglass** [comment]
#318 is still a problem when using the dotnet CLI to build.
