### ISSUE TITLE
Parameter in CONTAINS gives exception

### ISSUE THREAD

**Issue by cmeeren** [fsprojects/FSharp.Data.SqlClient#309]
I am trying to write a a parametrized `CONTAINS` statement:

```sql
CONTAINS(str1.String, @query)
```

But this gives the following error:

`Error FS3033: The type provider 'FSharp.Data.SqlCommandProvider' reported an error: The argument type "void type" is invalid for argument 2 of "CONTAINS". The batch could not be analyzed because of compile errors.`

Am I using it wrong, or is this a bug?

**Comment by cmeeren** [comment]
Workaround: Declare the variable:

```sql
DECLARE @input varchar(128)
SET @input = @query
```

Still, it would be great if this was not necessary.

**Comment by smoothdeveloper** [comment]
@cmeeren thanks for the report, could you check if this is related to the two stored procedures described in "Limitations" section: http://fsprojects.github.io/FSharp.Data.SqlClient/

I believe if this is the case, we should send those requests upstream to SQL Server team.

I don't think it is manageable to try to work around short coming of those underlying components with our own hacks, especially when a workaround is present and supported with an extra declaration in the SQL code, but if you can think of a safe way to implement this in the library, I'm eager to discuss it.

**Comment by cmeeren** [comment]
Thanks for getting back to me. Unfortunately, SQL is not my strong suit, so I wouldn't know what to look for in order to determine if it's related to the two stored procedures you use internally.

**Comment by cmeeren** [comment]
I can confirm that I get the same error when I run the following directly against the DB:


```sql
exec sys.sp_describe_undeclared_parameters N'
SELECT
  String
FROM
  [LanguageString]
WHERE
  CONTAINS(String, @shortCode)
'
```

```
Msg 4110, Level 16, State 6, Line 2
The argument type "void type" is invalid for argument 2 of "CONTAINS".
Msg 11501, Level 16, State 2, Line 2
The batch could not be analyzed because of compile errors.
```

**Comment by smoothdeveloper** [comment]
@cmeeren are you ok with closing this issue?

Ideally, we should report limitations on `sys.sp_describe_undeclared_parameters` to SQL Server team and see if they have plans to extend that.

**Comment by cmeeren** [comment]
Yes, feel free to close, and report to SQL Server team. :) Thanks!
