### ISSUE TITLE
SQL reader closed too early with FSharp.Core 4.5.3?

### ISSUE THREAD

**Issue by cmeeren** [fsprojects/FSharp.Data.SqlClient#319]
### Description

I don't know whether this belongs here or in the F# repo, but I'll try here first and cc @dsyme in case he knows immediately that some recent F# change may have caused this.

When upgrading from FSharp Core 4.5.2 to 4.5.3, at least one of my SQL queries consistently produces the following exception:

`System.InvalidOperationException: 'Invalid attempt to call FieldCount when reader is closed.'`

Simplified code:

```f#
// Signature is Async<Map<A, Map<B, C option>>>
async {
  use cmd =
    new SqlCommandProvider<"""
      SELECT ... FROM ... JOIN ... JOIN ... WHERE ...
      """, ConnectionStrings.mainCompile>(ConnectionStrings.main)
  let! res = cmd.AsyncExecute(...)
  return res |> Seq.choose ... |> Seq.groupBy fst |> Map.ofSeq |> Map.map ...
}
```

The exception happens on the last line (the `return` expression). It seems the SQL reader is closed before the `async` has returned, so when enumerating, a call is made to the reader's `FieldCount` which fails. I have no idea why this error occurs only for FSharp.Core 4.5.3 and not 4.5.2.

Workarounds (any of these work on their own):
* Use `Execute` instead of `AsyncExecute`
* Insert `Seq.toList` before or right after `Seq.choose` (after `Seq.groupBy` doesn't work)
* Insert `Seq.cache` before or right after `Seq.choose` (after `Seq.groupBy` doesn't work)

Note that for all I know, there may still be a race condition that can fail sometimes when using these workarounds.

I get this error in both FSharp.Data.SqlClient 1.8.3 and 2.0.1. For 2.0.1, it happens regardless of whether I'm targeting `net472` or `netstandard2.0`/`netcoreapp2.1`.

**Comment by cmeeren** [comment]
Note that I have another SQL query that retrieves a much smaller set of rows than the one I have problems with above, and the shorter query does not give the same error. This might provide some indications that there is a race condition somewhere.

**Comment by vasily-kirichenko** [comment]
IFAIK, you return lazy seq, but `cmd` is disposed as you leave `async { .. }` block, closing the reader as well. 

I find it logical.

**Comment by cmeeren** [comment]
Sorry, forgot to add that important fact. I do not return Seq.

**Comment by cmeeren** [comment]
The `groupBy` might be relevant in some way. I can insert `Seq.toList` or `seq.cache` before the `groupBy` and everything works, but I can't do it afterwards, even if I also evaluate the inner lists. I.e., the following doesn't fix the problem:

`Seq.groupBy ... |> Seq.toList |> Seq.map (fun (x, xs) -> x, Seq.toList xs) |> ...`

**Comment by cmeeren** [comment]
Yes, I now consistently do `Seq.toList` before doing anything else. Haven't had any problems, so that's a fair workaround.

By the way, is there any particular reason you use `array` instead of `list`?

**Comment by smoothdeveloper** [comment]
No strong reasons, but looking up length on array is o(1), for list it is o(n), and for memory compacity of data.

Also it still feels more natural to me using arrays vs linked lists.

**Comment by cmeeren** [comment]
Ok! By the way, if the docs don't already mention it, you might want to consider adding a note about eagerly evaluating the results before transforming them.

**Comment by smoothdeveloper** [comment]
This kind of falls under the same kind of issue one would have using LINQ or lazy IEnumerable, they need to be materialized before the context becomes invalid, or the handling of results in streaming needs to be carefully handled.

So I'm not sure how to tackle this from this library standpoint, as @vasily-kirichenko mentionned, it is logical.

After few such mishapps it becomes more natural to transition out of `seq` within the ambient context or to pass results one by one to a notification function for example.

When I want materialized results, I generally work with typed datatables + additional lookup structures rather than sequence of records. Do you think that would suit your usage?

**Comment by cmeeren** [comment]
> So I'm not sure how to tackle this from this library standpoint, as @vasily-kirichenko mentionned, it is logical.

Yes, I agree. The weird thing was that this only happened when upgrading FSharp.Core. Maybe some implementation details of `seq` changed.

> When I want materialized results, I generally work with typed datatables + additional lookup structures rather than sequence of records. Do you think that would suit your usage?

Sorry, I don't understand what you are referring to here.

**Comment by smoothdeveloper** [comment]
> Sorry, I don't understand what you are referring to here.

running smaller queries without joining all the sets for final projection, and doing the joins / aggregation in F#, by building dictionaries/lookups.

It is far lest idiomatic than ideal world SQL, but sometimes it can help when hitting performance issues that are too large to tackle in context of developping a report. 

Also, F# code can be composed/generalized, for example to parameterize aggregation, filtering and computations; doing this kind of stuff in SQL without code duplication can be arduous (dynamic SQL? 🙂).

**Comment by cmeeren** [comment]
> running smaller queries without joining all the sets for final projection, and doing the joins / aggregation in F#, by building dictionaries/lookups.

Yep, occasionally I have to do that. But if the datasets are sufficiently large and the queries sufficiently frequent, pure SQL (dynamic or not) might be the only viable option, doing everything on SQL server.

My point of confusion was typed datatables. I haven't worked with those before.
