### ISSUE TITLE
Index was outside the bounds of the array thrown for table-valued functions in 2.0.1

### ISSUE THREAD

**Issue by panesofglass** [fsprojects/FSharp.Data.SqlClient#323]
### Description

`Index was outside the bounds of the array.` thrown by `SqlCommandProvider` and `SqlProgrammabilityProvider` when accessing functions that specify `TOP 1`.

### Repro steps

Please provide the steps required to reproduce the problem

1. Define a `SqlProgrammabilityProvider` type.
2. Create a command instance of a table-valued function.
3. Attempt to call a table-valued function that returns a single result using `Execute` or `ExecuteSingle`.

### Expected behavior

In 1.8.2, the type provider returned the expected result as an `'a option` or `seq<'a>`.

### Actual behavior

Generated command throws `Index was outside the bounds of the array.` exception.

### Known workarounds

Replace the `SqlProgrammabilityProvider` generated command with a `SqlCommandProvider` command.

The above will not work for a TVP function.

### Related information 

* Operating system `Windows 10`
* Branch `2.0.1`
* Database versions and sample databases being used `Sql Server 2017`
* .NET Runtime, CoreCLR or Mono Version: `netstandard2.0`, `net461`
* Editing Tools (e.g. Visual Studio Version) `Visual Studio 2017 15.9.5`
* Lins to F# RFCs or entries on http://fslang.uservoice.com

**Comment by panesofglass** [comment]
I'm going to have to roll back several projects to use 1.8.2 and full framework again. :(

**Comment by vasily-kirichenko** [comment]
I cannot reproduce it:

```sql
create table dbo.Foo(col1 int, col2 nvarchar(max))
go

insert into dbo.Foo values(1, 'foo')
insert into dbo.Foo values(2, 'bar')
go

CREATE FUNCTION dbo.TableValuedFunc
(	
	@param1 int
)
RETURNS TABLE 
AS
RETURN 
(
	SELECT * from dbo.Foo
)
go
```
![image](https://user-images.githubusercontent.com/873919/50885651-61359300-13ff-11e9-8273-1be6e6390f10.png)

**Comment by panesofglass** [comment]
I will try to find time to write a repro sample. I can't tell whether or not this is a one-off issue. I tried reverting back to 1.8.2 and learned the same function fails in the same way on 1.8.2. Something seems very wrong, and it could be something in my environment, though other team members are seeing the same issue.

**Comment by panesofglass** [comment]
Still haven't had time to create a repro, but I've found fairly consistent issues with functions that use `SELECT TOP 1` and use the `ExecuteSingle` generated method. I'll try to create a repro after I get past my pending next release.

**Comment by panesofglass** [comment]
I cannot find a way to easily reproduce this. However, I'm seeing it on different functions across multiple versions of the type provider.
