### ISSUE TITLE
CommandTimeout for table Update

### ISSUE THREAD

**Issue by kkkmail** [fsprojects/FSharp.Data.SqlClient#324]
It seems impossible to specify command timeout for table `Update` command, e.g.
```
type SomeDataTable = SomeDB.dbo.Tables.SomeData
...
let t = new SomeDataTable()
let newRow = t.NewRow(...)
t.Update(conn) |> ignore
```
Hovering over `t.Update` does not show anything, which would resemble `commandTimeout`. Looking at the source: https://github.com/fsprojects/FSharp.Data.SqlClient/blob/master/src/SqlClient/DataTable.fs#L78-L79 shows that command timeout is not set.

**Comment by smoothdeveloper** [comment]
@kkkmail would you like to propose a PR for this?

**Comment by vasily-kirichenko** [comment]
Implemented via https://github.com/fsprojects/FSharp.Data.SqlClient/pull/339
