### ISSUE TITLE
Missing docs on dynamic filter

### ISSUE THREAD

**Issue by cmeeren** [fsprojects/FSharp.Data.SqlClient#326]
I wanted to see if it was possible to do dynamic filtering. The docs seem to contain a FAQ entry on this, but it stops just short of actually showing an example:

https://github.com/fsprojects/FSharp.Data.SqlClient/blob/fb8706f1d96c26c9ca68f3c98df2c5a4a057ba0e/docs/content/faq.fsx#L62-L69

![image](https://user-images.githubusercontent.com/7766733/52716668-95bce180-2f9f-11e9-8161-6956bc7957b1.png)

**Comment by jon49** [comment]
This might be what you are looking for https://github.com/fsprojects/FSharp.Data.SqlClient/blob/master/tests/SqlClient.Tests/OptionalParamsTests.fs#L8

Unless that is referring to something else. Like it would actually change the query for you. That would be pretty awesome. But I would be surprised if it had. But for static queries filter on different items is not a great idea from what I understand as SQL Server will optimize for one but not the other.

**Comment by smoothdeveloper** [comment]
@cmeeren, I believe @jon49 answer is relevant.

If you need to pass more complex data than a set of individual.

Consider using table valued parameters which are supported, both would be relevant way to get your input parameters passed in a type safe manner to your SQL code.

As with the "dynamic filters" feature, I'm not sure what it refers to, @dmitry-a-morozov, do you happen to remember what it is? (https://github.com/fsprojects/FSharp.Data.SqlClient/commit/1b99e2a84affa23315b5e990b79a85060e212c70#diff-79b0909ded88d95041fd23a87ee0a29dR61 "ver 1.7.4")

**Comment by cmeeren** [comment]
I wasn't thinking about the actual input parameters; I was more concerned with the actual SQL query. I am thinking of something like the following, where there's several possible filters for searching, and each filter may or may not be specified. This is AFAIK the normal way to do it in SQL:

```SQL
SELECT *
FROM Products
WHERE
  (@minPrice IS NULL OR Price >= @minPrice)
  AND (@maxPrice IS NULL OR Price <= @maxPrice)
  AND (@hasDiscount IS NULL OR HasDiscount = @hasDiscount)
```

Using static queries like these often requires adding `OPTION(RECOMPILE)` in order to avoid the compiler optimizing for the first set of input values and subsequently re-using the cached execution plan for other combinations of values, which may give terrible performance. But of course, with that flag the DB has to recompile the query each time, which also steals performance.

Another option is to use dynamic SQL, and simply not add the conditions for filters that are null. This gives several possible queries that the DB can safely cache and re-use the execution plans for. I am currently A/B-testing a rather complex search with dynamic vs. static, and the dynamic outperforms the static one in my particular case, but of course with some added maintenance cost since I get no compile-time check of the query.

When I saw the "How do I do dynamic filter" heading in the SqlClient docs, I thought that perhaps SqlClient might have some clever way to reconcile these two, but I guess this is simply not possible.

**Comment by smoothdeveloper** [comment]
@cmeeren thanks for all the great details!

I believe TVP can be useful when you need to pass sets of values with attributes, etc. That what I'd look for with a single static query, that would be the base plate.

If you can optimize it sanely with dynamic sql or other means for better performance, it would be interesting to share your insight or see if there is any use of the techniques for the library.

**Comment by cmeeren** [comment]
Sorry, not sure what you're after or how TVP factors into the kind of query I gave an example of above. Could you elaborate?

**Comment by smoothdeveloper** [comment]
```sql
create type my_complicated_procedure_filter_criterias table (operator varchar(3), logical_field_name varchar(max), value_as_datetime datetime, value_as_bit bit, ...)
```

in your query you could use that input table in plain SQL without dynamic SQL and probably cripled handling of operators, or you could use it to prepare a where clause and what to tables to join in a dynamic SQL for performance reason.

When dynamic SQL is not needed, you of course can define more specific table types for your input parameters, my example is kind of generic to give a broader idea of what you can achieve.

Would such approach work for you?

**Comment by cmeeren** [comment]
Sorry, I'm completely unfamiliar with `CREATE TYPE` and have barely touched on TVP.

Basically, my query is as follows (writing this from the top of my head, sorry for any syntax errors, I don't usually write much SQL). How would you solve this using your solution?

```sql
DECLARE @sql nvarchar(max) = '
  SELECT OrderId
  FROM Orders
  WHERE 1 = 1
'

IF @dateFrom IS NOT NULL BEGIN
  SET @sql += '
    AND Date >= @dateFrom
  '
END

IF @dateTo IS NOT NULL BEGIN
  SET @sql += '
    AND Date >= @dateTo
  '
END

IF @customerId IS NOT NULL BEGIN
  SET @sql += '
    AND CustomerId = @customerId
  '
END

-- etc.

DECLARE @paramlist nvarchar(max) = '
  @dateFrom datetime,
  @dateTo datetime,
  @customerId uniqueidentifier
'

EXEC sp_executesql @sql, @paramlist, @dateFrom, @dateTo, @customerId
WITH RESULT SETS (
  (OrderId uniqueidentifier NOT NULL)
)
```

**Comment by smoothdeveloper** [comment]
For the date stuff, I'd check if this is causing terrible performance or just works the same as not having the criteria in the query when passing null:

```sql
and (@dateFrom is null or t.Date >= @dateFrom)
and (@dateTo is null or t.Date <= @dateTo)
```

Using this technique is generally fine and defers the need for dynamic SQL.

**Comment by cmeeren** [comment]
Yes, but that method in general requires `OPTION RECOMPILE` to avoid terrible performance. So you don't get query plan caching, which has its own performance impacts. Also, it's what I already did as explained in [a previous comment](https://github.com/fsprojects/FSharp.Data.SqlClient/issues/326#issuecomment-470411976).

**Comment by smoothdeveloper** [comment]
@cmeeren 

> This gives several possible queries that the DB can safely cache and re-use the execution plans for. I am currently A/B-testing a rather complex search with dynamic vs. static, and the dynamic outperforms the static one in my particular case

I tend to stick to static sql so long the performance doesn't degrade and when I know input set is small enough for single pass projection.

But when working with larger datasets and performance deviates strongly from linear performance (SQL does that sometimes 😄), there are a lot of things that get into the picture, and dynamic SQL ranks among the highest I've seen in the wild.

Dynamic SQL is the only way I know (beside hypothetical DSL) to totally elide optional joins in complex queries.

I'm using the `with result sets ()` declaration to get typed results in F#.

From my perspective the drawback that dynamic SQL may not have correct shape is not related to F# nor this library but just the nature of dynamic SQL: similar to javascript's `eval` 🙂.

**Comment by cmeeren** [comment]
> From my perspective the drawback that dynamic SQL may not have correct shape is not related to F# nor this library but just the nature of dynamic SQL: similar to javascript's `eval` 🙂.

I agree, there is nothing this library can do about that (given the limitations of dynamic SQL). Using `with result sets` is still nice though, because it allows much simpler parsing in F# (similar to static SQL), whereas a reader seemed to require me to use recursive accumulator functions to build up the output list.

**Comment by smoothdeveloper** [comment]
> I needed to use an untyped reader,

@cmeeren, I've investigated a bit this matter around the time I posted #336, the library doesn't expose yet typed readers, but this could be added, it is not a small task (there is likely to be quotations in the way, + respecting architecture of the library, etc.), but probably something that can be tackled at some point if there is high interest.

I'm interested in typed data reader for purpose of streaming (no need to waste building records), and tracking progress of loading large datatables.

One issue, is that reader, like the connection, is a hot object, users of the library can shoot their foot if they mishandle it, similar as returning a `seq` in `async` and the connection getting closed while streaming.

**Comment by cmeeren** [comment]
Sounds nice. As I just mentioned in https://github.com/fsprojects/FSharp.Data.SqlClient/issues/319#issuecomment-484784726 I haven't worked with typed readers before, so that's new to me. Currently, dynamic SQL and `with result sets` covers all cases for me where I can't use simple static SQL.
