### ISSUE TITLE
Runtime query errors in async silently drops the async

### ISSUE THREAD

**Issue by cmeeren** [fsprojects/FSharp.Data.SqlClient#330]
### Description

This caused me some hours of confusion today and I would consider this a critical bug.

When dynamic SQL contains undeclared variables, no exception is raised, but the `async` is silently dropped all the way up. (I haven't tested using sync.)

### Repro steps

In the code below, the dynamic SQL gets passed a variable named `@x` (through `sp_executesql`), but the actual SQL uses a (deliberately mistyped) parameter `@y`. (Mistyped parameter names can, of course, frequently occur when using dynamic SQL, and unfortunately dynamic SQL is sometimes required, e.g. as described in https://github.com/fsprojects/FSharp.Data.SqlClient/issues/326#issuecomment-470411976).

```f#
let test =
  async {
    use cmd =
      new SqlCommandProvider<
        "
        DECLARE @_x varchar(max) = @x
        DECLARE @sql nvarchar(max) = 'SELECT 1 WHERE @y = 1'
        EXEC sp_executesql @sql, N'@x varchar(max)', @_x
        ",
        myConnectionString,
        ResultType = ResultType.DataReader>
        (myConnectionString)
    let! res = cmd.AsyncExecute(x = "foo")
    return ()
  }

let testLoop =
  async {
    while true do
      do! Async.Sleep 1000
      printfn "Running test"
      do! test
      printfn "Test complete"
  }

Async.Start testLoop
```

### Expected behavior

Should output `Running test` and then throw an exception with an error similar to what you get if you run the SQL directly in e.g. SQL Server Management Studio (`Must declare the scalar variable "@y".`).

### Actual behavior

Outputs `Running test` and then nothing. `AsyncExecute` causes the async to be silently cancelled all the way up. There are no exceptions to catch. The loop ends, and there is nothing to indicate that anything bad happens.

### Known workarounds

None.

### Related information 

* Win 10
* Latest nuget
* SQL Server 2016
* .NET 4.7.2
* VS 2017

**Comment by smoothdeveloper** [comment]
@cmeeren I'm getting the following runtime error:

```
Running test
System.Data.SqlClient.SqlException (0x80131904): Must declare the scalar variable "@y".
   at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
>    at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at System.Data.SqlClient.SqlDataReader.TryConsumeMetaData()
   at System.Data.SqlClient.SqlDataReader.get_MetaData()
   at System.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString, Boolean isInternal, Boolean forDescribeParameterEncryption, Boolean shouldCacheForAlwaysEncrypted)
   at System.Data.SqlClient.SqlCommand.CompleteAsyncExecuteReader(Boolean isInternal, Boolean forDescribeParameterEncryption)
   at System.Data.SqlClient.SqlCommand.InternalEndExecuteReader(IAsyncResult asyncResult, String endMethod, Boolean isInternal)
   at System.Data.SqlClient.SqlCommand.EndExecuteReaderInternal(IAsyncResult asyncResult)
   at System.Data.SqlClient.SqlCommand.EndExecuteReader(IAsyncResult asyncResult)
   at <StartupCode$FSharp-Core>.$Control.callback@1784.Invoke(IAsyncResult ar)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.FSharp.Control.AsyncBuilderImpl.commit[a](Result`1 res)
   at Microsoft.FSharp.Control.CancellationTokenOps.RunSynchronously[a](CancellationToken token, FSharpAsync`1 computation, FSharpOption`1 timeout)
   at Microsoft.FSharp.Control.FSharpAsync.RunSynchronously[T](FSharpAsync`1 computation, FSharpOption`1 timeout, FSharpOption`1 cancellationToken)
   at <StartupCode$FSI_0005>.$FSI_0005.main@() in C:\work\fdstest.fsx:line 2
ClientConnectionId:1e3ef132-9c23-4595-90ed-5ee0c96da0c8
Error Number:137,State:2,Class:15
Stopped due to error
```

but by the look of it, I don't see this as an issue, the statement itself is checked against SQL Server and has valid syntax, as usual when you are doing dynamic SQL, you are a bit on your own in terms of making sure the generated SQL will be doing what you expect.

Am I missing something?

**Comment by cmeeren** [comment]
Please see the enclosed repro solution. When I run it, whether in release or debug, I get the behavior I experience. Can you reproduce using this solution?

(In case you can't, I have also attached compiled binaries, I think you can run them using `dotnet SqlRepro.dll`.)

[SqlRepro.zip](https://github.com/fsprojects/FSharp.Data.SqlClient/files/2944691/SqlRepro.zip)
[Compiled.zip](https://github.com/fsprojects/FSharp.Data.SqlClient/files/2944690/Compiled.zip)

Note that the bug only occurs for `AsyncExecute`. If I call `Execute` I get an exception as expected.

**Comment by smoothdeveloper** [comment]
I've tried the following script with the result above:

```fsharp
#load ".paket/load/net462/fsharp.data.sqlclient.fsx"
let [<Literal>] myConnectionString = @"Data Source=(localdb)\v12.0;Initial Catalog=master;Trusted_Connection=True"

open FSharp.Data
let test =
  async {
    use cmd =
      new SqlCommandProvider<
        "
        DECLARE @_x varchar(max) = @x
        DECLARE @sql nvarchar(max) = 'SELECT 1 WHERE @y = 1'
        EXEC sp_executesql @sql, N'@x varchar(max)', @_x
        ",
        myConnectionString,
        ResultType = ResultType.DataReader>
        (myConnectionString)
    let! res = cmd.AsyncExecute(x = "foo")
    //let res = cmd.Execute(x = "foo")
    return ()
  }

let testLoop user req =
  async {
    while true do
      do! Async.Sleep 1000
      printfn "Running test"
      do! test
      printfn "Test complete"
    return [1]
  }

Async.RunSynchronously (testLoop "foo" "foo")
```

When I want to catch the error outside my async code, I use `Async.Catch` to combine with async values and wrap them in a `Result`, maybe that could help you deal with that case?

**Comment by cmeeren** [comment]
The problem is that there is no exception to catch in the first place. I would expect `AsyncExecute` to throw an exception that I can catch and log. But instead, the whole async expression is silently cancelled. If I use `Execute` (not async), I get an exception. But if I use `AsyncExecute`, there is no exception, only silent cancelling of the async workflow.

Please try the repro solution I attached above. It demonstrates what I mean.

**Comment by cmeeren** [comment]
Wait a minute. I tried inserting `try ... with` and it successfully catches the exception. It might be the case that this is either a tooling issue (VS debugger) or I have completely misunderstood how `async` exception handling works. Will investigate further.

**Comment by cmeeren** [comment]
Okay, I am thoroughly confused. From what I understand, `Async.Start comp` will not propagate any exception raised in `comp` to the caller (that called `Async.Start`). But what I observe doesn't make sense to me. Based on the repro solution I posted above (please have a look at it):

* If I use `AsyncExecute`, I get the behavior I described. No exception, even after telling VS to stop at all exceptions. This is confusing; I would expect VS to break at the exception.
* If I use `Execute`, I get the exception I expect. But I find the following points confusing:
   * VS breaks at the exception even though I tell it not to break at anything at all
   * The exception brings down the whole console app. This makes no sense to me, because even though `Execute` is sync, it's still called from inside an async computation passed to `Async.Start`, so AFAIK no exception raised in the async computation should be able to bring down the whole app.

Do you have any clarification?

**Comment by smoothdeveloper** [comment]
@cmeeren, it is better to guard async computation either with explicit try / catch within it as you mention, or for example using `comp |> Async.Catch |> Async.Start`.

From what I understand, the issue you have is related to the async workflow rather than the library, I could be mistaken; not sure if any other maintainer can confirm.

I've not looked much into the VS debugger behaviour, but as you've seen having the guard allows you to break & step.

Do you have a chance to submit a failing test in a PR, with the smallest possible sample?

**Comment by cmeeren** [comment]
I believe that this is partly explained by misunderstanding on my part regarding how `Async.Start` handles exceptions. However, I can't see that this explains the discrepancy between `Execute` and `AsyncExecute`.

As an explaination, please consider the following code:

```f#
open System
open FSharp.Data

let [<Literal>] connStr = @"Data Source=localhost\SQLEXPRESS;Trusted_Connection=Yes;"

let getCmd () =
  new SqlCommandProvider<
    "EXEC sp_executesql 'INVALID'",
    connStr, ResultType = ResultType.DataReader>(connStr)
    
let testAsyncExecute =
  async {
    use cmd = getCmd ()
    printfn "Calling AsyncExecute"
    do! cmd.AsyncExecute() |> Async.Ignore
    printfn "Called AsyncExecute"
  }

let testExecute =
  async {
    use cmd = getCmd ()
    printfn "Calling Execute"
    cmd.Execute() |> ignore
    printfn "Called Execute"
  }


[<EntryPoint>]
let main argv =
  Async.Start testExecute
  Console.ReadLine() |> ignore
  0
```

There are two async workflows here. The only difference between them is whether they call `Execute` or `AsyncExecute`. Both of the calls are however in an `async` computation.

The code at the bottom starts one async computation using `Async.Start`. According to my understanding, it should then [start on the thread pool](https://msdn.microsoft.com/en-us/visualfsharpdocs/conceptual/async.start-method-%5Bfsharp%5D), and [exceptions should not be propagated to the caller](https://medium.com/jettech/f-async-guide-eb3c8a2d180a#0772). This is the behavior I see when I start `testAsyncExecute`. But when I instead start `testExecute`, the app crashes; in other words, the exception seems to indeed be propagated to the caller even though `Async.Start` is used and the computations run on a thread pool thread (I double-checked that last point using `System.Threading.Thread.CurrentThread.ManagedThreadId` in the CEs).

Do you have any insights that might clear up the confusion?

**Comment by cmeeren** [comment]
[This answer to an SO question I just asked](https://stackoverflow.com/a/55694256/2978652) clarifies one point: Any exception on any thread will bring down an app that does not have any exception handling. So that explains why the app crashes even when using `Async.Start`.

This leaves one final conundrum: Why doesn't that happen with `AsyncExecute`? It, too, throws an exception (as is evident when enclosing it with `try ... with`), but without `try ... with`, there are absolutely no traces of an exception anywhere - the async expression just stops, and the app continues running.

AFAIK this shouldn't happen (at least I can't explain it), and it suggests to me that there's something weird about the implementation of `AsyncExecute`.

**Comment by smoothdeveloper** [comment]
Closing old discussion.
