### ISSUE TITLE
Allow discriminated union as option for SqlEnumProvider

### ISSUE THREAD

**Issue by VTJDailey** [fsprojects/FSharp.Data.SqlClient#333]
I'd be interested in a different code generation option for SqlEnumProvider, and would be willing to try and implement myself if I knew it would be accepted into the project.

The current SqlEnumProvider seems focused more on being fed quickly back into another sql command by providing the key values as constants.  I'd like to use them more in the logic of a program by providing an option to generate the values as a plain discriminated union to leverage the 'Incomplete pattern matches on this expression' error checking, and with associated functions to access the metadata.

Here's a complete example of what I'm suggesting (including a dummied up 3rd column in the query):

```
type ShipMethod = 
    SqlEnumProvider<"SELECT Name, ShipMethodID, Name + ' - ' + CONVERT(nvarchar, ModifiedDate, 101) AS ExtendedName", connStr, 
                     Kind = SqlEnumKind.DiscriminatedUnion>

```
would generate the equivalent of this code:

```
type ShippingMethod = 
    | ``XRQ - TRUCK GROUND``
    | ``ZY - EXPRESS``
    | ``OVERSEAS - DELUXE``
    | ``OVERNIGHT J-FAST``
    | ``CARGO TRANSPORT 5``
module ShippingMethod =
    let tryFromShipMethodId = function
                              | 1 -> Some ``XRQ - TRUCK GROUND``
                              | 2 -> Some ``ZY - EXPRESS``
                              | 3 -> Some ``OVERSEAS - DELUXE``
                              | 4 -> Some ``OVERNIGHT J-FAST``
                              | 5 -> Some ``CARGO TRANSPORT 5``
                              | _ -> None
    let fromShipMethodId id = match tryFromShipMethodId id with
                              | Some v -> v
                              | None -> failwith (sprintf "Cannot parse ShippingMethod from key %A" id)

    let toShipMethodId = function
                         | ``XRQ - TRUCK GROUND`` -> 1
                         | ``ZY - EXPRESS`` -> 2
                         | ``OVERSEAS - DELUXE`` -> 3
                         | ``OVERNIGHT J-FAST`` -> 4
                         | ``CARGO TRANSPORT 5`` -> 5
    let toName = function
                 | ``XRQ - TRUCK GROUND`` -> "XRQ - TRUCK GROUND"
                 | ``ZY - EXPRESS`` -> "ZY - EXPRESS"
                 | ``OVERSEAS - DELUXE`` -> "OVERSEAS - DELUXE"
                 | ``OVERNIGHT J-FAST`` -> "OVERNIGHT J-FAST"
                 | ``CARGO TRANSPORT 5`` -> "CARGO TRANSPORT 5"
    let toExtendedName = function
                         | ``XRQ - TRUCK GROUND`` -> "XRQ - TRUCK GROUND - 06/01/2002"
                         | ``ZY - EXPRESS`` -> "ZY - EXPRESS - 06/01/2002"
                         | ``OVERSEAS - DELUXE`` -> "OVERSEAS - DELUXE - 06/01/2002"
                         | ``OVERNIGHT J-FAST`` -> "OVERNIGHT J-FAST - 06/01/2002"
type ShippingMethod with 
    member this.ShipMethodId = this |> ShippingMethod.toShipMethodId
    member this.Name = this |> ShippingMethod.toName
    member this.ExtendedName = this |> ShippingMethod.toExtendedName

```

I'm not extremely experienced with type providers, but I assume there would be no technical problem with implementing it this way.  

Would this feature be pulled into the project if I implemented it over the next couple of months?

**Comment by vasily-kirichenko** [comment]
Unfortunately, type providers cannot generate discriminated unions, records and generic types.

**Comment by smoothdeveloper** [comment]
@VTJDailey @vasily-kirichenko is right that the TP SDK doesn't have facilities to expose F# types.

although I think it really depends how bad this feature is wanted, and if we can find IL generation code that could basically emit what makes a DU a DU to the F# compiler.

It's a lot of TP sdk and FCS headache ahead though if someone is going to do this, I wonder if @7sharp9  hasn't worked on similar stuff, but for records and what has been experience with dealing with such code.

I can't find issue on https://github.com/fsprojects/FSharp.TypeProviders.SDK that is requesting support for emitting more F# types, any idea if this is already tracked somewhere?

**Comment by VTJDailey** [comment]
I'd say that's deeper than I'm really interested in going at this point.  Other than a small bug fix on this project I haven't done any other type provider work and this doesn't seem like the right place to start  :)  

Anyway, there's at least one other idea I have to suggest that I'll put together tomorrow, and I should read through the open issues list too.

**Comment by smoothdeveloper** [comment]
@VTJDailey thanks for the feedback, and please feel free to submit more suggestions, they are welcome.

There are probably things that are more at reach that can be done in the library, if you are interested in contributing, please feel free to comment here or engage discussion, most of the maintainers of this library are on fsharp.org slack, and monitoring code comments / issues / PR via github.

Are you ok to close this issue?

**Comment by VTJDailey** [comment]
Yes, go ahead and close it, that's fine.

I probably will engage more later on -- I've got a period of time now with less paid work and want to spend some time boosting open source libraries that I've gotten good use out of.

**Comment by smoothdeveloper** [comment]
Couple of links:

https://stackoverflow.com/questions/20421160/providing-a-discriminated-union-from-an-f-type-provider

https://github.com/fsharp/fslang-suggestions/issues/212#issuecomment-474747251
