### ISSUE TITLE
2.0.3 and 2.0.4 are not published to Nuget

### ISSUE THREAD

**Issue by cmeeren** [fsprojects/FSharp.Data.SqlClient#344]
The [changelog](https://github.com/fsprojects/FSharp.Data.SqlClient/blob/52f89323a128c290bd084091c0bf7e7250f5992e/RELEASE_NOTES.md) lists both 2.0.3 and 2.0.4, but the latest version on Nuget is 2.0.2.

![image](https://user-images.githubusercontent.com/7766733/58712233-7b790900-83c0-11e9-932d-1d85ad9af923.png)

**Comment by smoothdeveloper** [comment]
@cmeeren, I've tried to get the nuget publish step to work but haven't succeeded yet.

If another maintainer has all of this cobbled up or ping me on fsharp.org slack to help me getting the release out, that would be greatly appreciated.

**Comment by cmeeren** [comment]
Perhaps the current releases could be published manually?

**Comment by vasily-kirichenko** [comment]
Done along with https://github.com/fsprojects/FSharp.Data.SqlClient/issues/324
