### ISSUE TITLE
Decimal values in table valued parameters getting rounded

### ISSUE THREAD

**Issue by hejoco** [fsprojects/FSharp.Data.SqlClient#345]
### Description

Decimal value passed to stored procedure via user-defined table type gets rounded.

### Repro steps
```sql
CREATE TYPE [dbo].[Decimal_Test_Tvp] AS TABLE(
	[Quantity] [DECIMAL](22,8) NULL)

```
```sql
CREATE PROCEDURE [dbo].[Decimal_Test] (@tvp dbo.Decimal_Test_Tvp READONLY)
AS
BEGIN
    SELECT Quantity FROM @tvp
END

```
```fsharp
       type Provider = SqlProgrammabilityProvider<...>
       type DecimalTestTvp = Provider.dbo.``User-Defined Table Types``.Decimal_Test_Tvp

        let tvp = 
            DecimalTestTvp ( Some 1.2345M)
            |> Seq.singleton

        use cmd = new Provider.dbo.Decimal_Test(connectionString)

        let value = cmd.Execute(tvp)

```
### Expected behavior

value should equal 1.2345

### Actual behavior

value is equal to 1.0 

### Known workarounds

Redefine the decimal column in the table valued parameter to be of type string. Convert the decimal value to string and set that in the table valued parameter. Then inside the stored procedure convert the string back to decimal(22,8).

**Comment by smoothdeveloper** [comment]
The new 2.0,7 release has the fix. Thanks @suou-ryuu for your help with the fix. Thanks @hejoco for the report and test case.
