### ISSUE TITLE
Improve "dynamic creation of offline MDF" docs

### ISSUE THREAD

**Issue by cmeeren** [fsprojects/FSharp.Data.SqlClient#356]
The [Dynamic creation of offline MDF](http://fsprojects.github.io/FSharp.Data.SqlClient/dynamic%20local%20db.html) docs don't work out of the box. For example, I had to replace `(localdb)\v11.0` with `(localdb)\MSSQLLocalDB` (perhaps v11.0 is outdated?). Furthermore, the script contains e.g. `NAME = Sales_dat,` which is a name that doesn't make sense (I guess it's copied from [here](https://docs.microsoft.com/en-us/sql/t-sql/statements/create-database-transact-sql?view=sql-server-2017#b-creating-a-database-that-specifies-the-data-and-transaction-log-files)).

In any case, I have experimented a lot with this stuff today, and I have further suggestions for improvements. Below is a cleaned-up and improved PS script as well as MSBuild stuff that gives the following benefits:

* Supports creating more than one database (with a single parametrized PS script)
* DBs are rebuilt if their corresponding SQL scripts have changed, or if the PS script has changed
* Project is rebuilt if the PS script has changed
* Project is rebuilt if any SQL file has changed (both the DB creation scripts, and any other SQL scripts that SqlClient might use though the `SqlFile` TP)
* Incremental build - each DB is only built it its DB SQL script or the PS script has changed
* PS script throws less warnings about missing files and DBs

Would it be useful to have these changes integrated into the aforementioned docs page?

Note that I'm no expert in PowerShell or MSBuild, so there might be room for improvements.

The PS script:

```powershell
param(
  [Parameter(Mandatory=$true)][String]$DbName,
  [Parameter(Mandatory=$true)][String]$DbScript
)


$detach_db_sql = @"
IF (SELECT COUNT(*) FROM sys.databases WHERE name = '$DbName') > 0
  EXEC sp_detach_db @dbname = N'$DbName'
"@

$detach_db_sql | Out-File "detachdb.sql"
sqlcmd -S "(LocalDB)\MSSQLLocalDB" -i "detachdb.sql"
Remove-Item "detachdb.sql"

if (Test-Path "$PSScriptRoot\$DbName.mdf") { Remove-Item "$PSScriptRoot\$DbName.mdf" }
if (Test-Path "$PSScriptRoot\$DbName.ldf") { Remove-Item "$PSScriptRoot\$DbName.ldf" }

$create_db_sql = @"
CREATE DATABASE $DbName
ON (
  NAME = ${DbName}_dat,
  FILENAME = '$PSScriptRoot\$DbName.mdf'
)
LOG ON (
  NAME = ${DbName}_log,
  FILENAME = '$PSScriptRoot\$DbName.ldf'
)
"@

$create_db_sql | Out-File "createdb.sql"
sqlcmd -S "(LocalDB)\MSSQLLocalDB" -i "createdb.sql"
Remove-Item "createdb.sql"

sqlcmd -S "(LocalDB)\MSSQLLocalDB" -i "$DbScript"

$detach_db_sql | Out-File "detachdb.sql"
sqlcmd -S "(LocalDB)\MSSQLLocalDB" -i "detachdb.sql"
Remove-Item "detachdb.sql"
```

The MSBuild stuff (the below assumes that the scripts/DBs are placed in an `SQL` subdir; if the project root is preferred, simply remove all occurrences of `SQL\`):

```fsproj
<ItemGroup>
  <SqlFiles Include="**\*.sql" />
  <BuildDbPsScript Include="SQL\createDb.ps1" />
  <BuildDbSqlScripts Include="SQL\create_myDb1.sql" DbName="Db1" />
  <BuildDbSqlScripts Include="SQL\create_myDb2.sql" DbName="Db2" />
  <UpToDateCheckInput Include="@(SqlFiles)" />
  <UpToDateCheckInput Include="@(BuildDbPsScript)" />
  <UpToDateCheckInput Include="@(BuildDbSqlScripts)" />
  <UpToDateCheckInput Include="@(BuildDbSqlScripts -> 'SQL\%(DbName).mdf')" />
  <UpToDateCheckInput Include="@(BuildDbSqlScripts -> 'SQL\%(DbName).ldf')" />
</ItemGroup>

<Target Name="BuildDb" BeforeTargets="BeforeBuild" Inputs="@(BuildDbSqlScripts);@(BuildDbPsScript)" Outputs="SQL\%(BuildDbSqlScripts.DbName).mdf;SQL\%(BuildDbSqlScripts.DbName).ldf">
  <Message Text="DB build scripts changed. Building out database %(BuildDbSqlScripts.DbName) using script %(BuildDbSqlScripts.Identity)" Importance="High" />
  <Exec Command="PowerShell -NoProfile -ExecutionPolicy Bypass -Command &quot;&amp; { @(BuildDbPsScript) -DbName %(BuildDbSqlScripts.DbName) -DbScript %(BuildDbSqlScripts.Identity) }&quot;" />
</Target>

<Target Name="TouchProjectFileIfSqlOrDbChanged" BeforeTargets="BeforeBuild" Inputs="@(SqlFiles);@(BuildDbPsScript);@(BuildDbSqlScripts)" Outputs="$(MSBuildProjectFile)">
  <Message Text="SQL or DB files changed. Changing project file modification time to force recompilation." Importance="High" />
  <Exec Command="PowerShell -NoProfile -ExecutionPolicy Bypass -Command &quot;(dir $(MSBuildProjectFile)).LastWriteTime = Get-Date&quot;" />
</Target>
```

**Comment by smoothdeveloper** [comment]
> Would it be useful to have these changes integrated into the aforementioned docs page?

Yes, the documentation is here:

https://github.com/fsprojects/FSharp.Data.SqlClient/blob/master/docs/content/dynamic%20local%20db.fsx

Could you make a PR with the bits that need adjustments?

To run the documentation locally: https://github.com/fsprojects/FSharp.Data.SqlClient/blob/1e5d276dc4842f8e8bdfb28995fc603489b2e438/CONTRIBUTING.md#contributing-to-the-docs

**Comment by cmeeren** [comment]
Will do!
