### ISSUE TITLE
FS3033 error from SqlProgrammabilityProvider when stored procedure in SqlAzure uses sp_getapplock

### ISSUE THREAD

**Issue by sgryt** [fsprojects/FSharp.Data.SqlClient#372]
### Description

We get the following error (both from Intellisense and compilation) when a stored procedure in SQL Azure calls the built-in sp_getapplock function:

```
Severity	Code	Description	Project	File	Line	Suppression State
Error	FS3033	The type provider 'FSharp.Data.SqlProgrammabilityProvider' reported an error: The metadata could not be determined because statement 'exec @result = sys.xp_userlock 0, @dbid, @DbPrincipal, @Resource, @mode, @owner, @LockTimeout' in procedure 'sp_getapplock' invokes an extended stored procedure.
```

### Repro steps

1: Use SqlProgrammabilityProvider to invoke a custom stored procedure which uses the built-in sp_getapplock function. 

2: Observe the compilation and Intellisense errors above.

### Expected behavior

No errors. I would expect to be able to compile the source code.

### Actual behavior

Compilation (and Intellisense) error is observed

### Known workarounds

N/A

### Related information 

* Operating system
 Windows 10 and Windows Server 2016
* Branch 
 Latest
* Database versions and sample databases being used
 SQL Azure
* .NET Runtime, CoreCLR or Mono Version
 .NET Framework 4.7.2
* Editing Tools (e.g. Visual Studio Version)
 VS 2017 Pro
* Lins to F# RFCs or entries on http://fslang.uservoice.com
 N/A

**Comment by smoothdeveloper** [comment]
@sgryt can you check what `sys.sp_describe_undeclared_parameters` and `sys.sp_describe_first_result_set` give for your statement?

If the stored procedure is executing dynamic statements, those needs to be assorted with `with result sets` and a static description of the returned result set.

This is a known limitations listed at the bottom of https://fsprojects.github.io/FSharp.Data.SqlClient/.

**Comment by sgryt** [comment]
@smoothdeveloper The specific statement only returns an error code, not a result set. I haven't got access to the `sys` schema in the database, but I will ask a colleague to get back with the output of the two procedures you mention.

It does, however, call other procedures internally, and some way down the call-graph, the sp_getapplock is called.

**Comment by sgryt** [comment]
@smoothdeveloper 

The first one (`sys.sp_describe_undeclared_parameters`) returns no results.

The second one (`sys.sp_describe_first_result_set`) returns 1 row:

"is_hidden","column_ordinal","name","is_nullable","system_type_id","system_type_name","max_length","precision","scale","collation_name","user_type_id","user_type_database","user_type_schema","user_type_name","assembly_qualified_type_name","xml_collection_id","xml_collection_database","xml_collection_schema","xml_collection_name","is_xml_document","is_case_sensitive","is_fixed_length_clr_type","source_server","source_database","source_schema","source_table","source_column","is_identity_column","is_part_of_unique_key","is_updateable","is_computed_column","is_sparse_column_set","ordinal_in_order_by_list","order_by_is_descending","order_by_list_length","tds_type_id","tds_length","tds_collation_id","tds_collation_sort_id"
"False","1","null","False","56","int","4","10","0","null","null","null","null","null","null","null","null","null","null","False","False","False","null","null","null","null","null","False","null","False","True","False","null","null","null","56","4","null","null"

HTH ?

**Comment by smoothdeveloper** [comment]
@sgryt
> The specific statement only returns an error code

since there is no result sets, I'd go with specifying `with result sets none` for that `exec` statement used to assign the value.

probably something like this:

```sql
exec @result = sys.xp_userlock 0, @dbid, @DbPrincipal, @Resource, @mode, @owner, @LockTimeout
with result sets none
```
Please let us know if that solves it.

**Comment by sgryt** [comment]
@smoothdeveloper OK, that fixed the compilation problem (after restarting VS, though, there seems to be some caching involved somewhere) 👍 

Thanks a lot for your help !
