### ISSUE TITLE
Microsoft.Data.SqlClient

### ISSUE THREAD

**Issue by jackfoxy** [fsprojects/FSharp.Data.SqlClient#389]
### Description

Microsoft.Data.SqlClient replaces System.Data.SqlClient as the fully dotnet compliant data access driver for Sql Server. Not implementing this upgrade causes issues with projects that implement Microsoft.Data.SqlClient separately.

https://devblogs.microsoft.com/dotnet/introducing-the-new-microsoftdatasqlclient/

**Comment by smoothdeveloper** [comment]
Closing as duplicate, this is tracked #374.

I'm not sure how this will land yet, but getting a branch that targets the new client library is the first step.
