### ISSUE TITLE
.NET 6 support

### ISSUE THREAD

**Issue by vasily-kirichenko** [fsprojects/FSharp.Data.SqlClient#415]
Create a .NET 6 console app, add the package, look at the error:

![image](https://user-images.githubusercontent.com/873919/148932965-f6be172d-f435-4de1-bb3b-b8c0a9ef677d.png)

```
0>------- Started building project: SqlProviderTest
0>F:\SqlProviderTest\SqlProviderTest\Program.fs(5,22): Error FS3033 : The type provider 'FSharp.Data.SqlCommandProvider' reported an error: Could not load file or assembly 'System.Data.SqlClient, Version=4.4.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. Reference assemblies should not be loaded for execution.  They can only be loaded in the Reflection-only loader context. (0x80131058)
0>F:\SqlProviderTest\SqlProviderTest\Program.fs(5,22): Error FS3033 : The type provider 'FSharp.Data.SqlCommandProvider' reported an error: Could not load file or assembly 'System.Data.SqlClient, Version=4.4.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. Reference assemblies should not be loaded for execution.  They can only be loaded in the Reflection-only loader context. (0x80131058)
0>------- Finished building project: SqlProviderTest. Succeeded: False. Errors: 2. Warnings: 0
```

**Comment by vasily-kirichenko** [comment]
OK, everything works if the SDK bundled with VS 2022 is used. Crazy as hell, but it works.

**Comment by cmeeren** [comment]
Is this considered fixed? I am trying to compile with the latest Rider, but I get this error. It only compiles in VS2022.

I don't really care that much since I am migrating away from this library, but I thought I'd mention it.

**Comment by Kurren123** [comment]
I'm also running into this issue. Unfortunately need to use another sql library to move forward. Shame as this one is so slick.

**Comment by smoothdeveloper** [comment]
@Kurren123, could you share the version of dotnet sdk, just to trace some of the info on which it fails. Do you have the VS 2022 build tools installed in case it solves the issue and you don't have VS itself?

**Comment by Kurren123** [comment]
> @Kurren123, could you share the version of dotnet sdk, just to trace some of the info on which it fails. Do you have the VS 2022 build tools installed in case it solves the issue and you don't have VS itself?

`dotnet --version` is 6.0.301. It does work on visual studio 2022, however my team don't all have access to that.

**Comment by iuribrindeiro** [comment]
Same here, it doesn't work in vscode or Rider. Didn't try VS yet.
