### ISSUE TITLE
FSharp.Data.SqlCommandProvider throws error if statement/proc uses temp table

### ISSUE THREAD

**Issue by unuunc** [fsprojects/FSharp.Data.SqlClient#55]
I have a stored procedure which uses temp tables when i try to execute that I get following error
"The type provider 'FSharp.Data.SqlCommandProvider' reported an error: The metadata could not be determined because statement ... uses a temp table."

**Comment by ScottHutchinson** [comment]
Is there no alternative to the sys.sp_describe_first_result_set stored procedure that would work with temporary tables or table variables? Maybe as an option, in case it has any negative side effects, like slowness?

**Comment by smoothdeveloper** [comment]
@ScottHutchinson please check #277 #278 this is feature proposal with a pending PR implementing it to deal with temp tables.
