### ISSUE TITLE
FSharp.Core 4.4.0.0 gets referenced when using Visual Studio 2015 Preview

### ISSUE THREAD

**Issue by ctaggart** [fsprojects/FSharp.Data.SqlClient#79]
I created an example `FSharp.Data.SqlClient` console app to isolate a problem I'm having using it with `Visual Studio 2015 Preview`. The app simple runs a query against a hosted `AdventureWorks` on Azure. It prints the top the first 10 people using `select top 10 FirstName, LastName from person.person`.

When running from Visual Studio 2013 it works.
![image](https://cloud.githubusercontent.com/assets/80104/5100219/59216d1a-6f58-11e4-8a5b-5d5d93484666.png)

When I use Visual Studio 2015 Preview, I get:
![image](https://cloud.githubusercontent.com/assets/80104/5100253/f4bd9992-6f58-11e4-991a-108007b620e2.png)

The build does give this warning:
![image](https://cloud.githubusercontent.com/assets/80104/5100268/1cbcd228-6f59-11e4-91a0-601c0bbda692.png)

For some reason, the PeopleData.dll is ending up with a reference to `4.4.0.0`, but I'm not sure how.
![image](https://cloud.githubusercontent.com/assets/80104/5100292/80d6fd9c-6f59-11e4-9f6a-7d93c5b8e596.png)

Here are the steps to reproduce:

```
PS> git clone https://github.com/ctaggart/Paket09x.git -b PeopleSql
PS> .\Paket09x\PeopleSql.sln
```

Rebuild solution. (It is not using Paket.)

**Comment by ctaggart** [comment]
According to Kevin, it is something wrong with this Type Provider implementation.

**Comment by ctaggart** [comment]
Pretty still affects the latest Visual Studio 2015 build. I'm sure it will still affect VS 2015 RTM.
Work-a-round:
```
<bindingRedirect oldVersion="0.0.0.0-4.4.0.0" newVersion="4.3.1.0" />
```

**Comment by dmitry-a-morozov** [comment]
@ctaggart We're long way from resolving this issue.
See https://github.com/Microsoft/visualfsharp/pull/478

**Comment by LessIsMore1** [comment]
Same problem with creating and Web Api using
*VS 2015 Upd1
*ASP.NET5 RC1 Upd1
*SqlClient 1.8

**Comment by dmitry-a-morozov** [comment]
@LessIsMore1 As of now the only solution is to use binding redirect.

**Comment by dsevastianov** [comment]
@LessIsMore1 looks like it was fixed, are you still experiencing this?

**Comment by lessismore1** [comment]
@dsevastianov it is fixed! Sorry for the VERY late reply :)
