### ISSUE TITLE
Reuse generated records / be able to provide your own records

### ISSUE THREAD

**Issue by jorgef** [fsprojects/FSharp.Data.SqlClient#89]
Hi,

I have a few queries that all return the same set of columns (different filtering) e.g.:

SELECT Id, Name, Age FROM Customers WHERE id = @Id
SELECT Id, Name, Age FROM Customers WHERE Age > 18

When reading the results, I need to transform the result to my own 'Customer' record like this (the real code is more complex):

result |> (fun r -> { Id = r.Id; Name = r.Name; Age = r.Age } : Customer)
results |> Seq.map (fun r -> { Id = r.Id; Name = r.Name; Age = r.Age } : Customer)

It would be great to be able to reuse the same generated record for all the queries so I can generalise that function:

let toCustomer (r: GeneratedRecord) = { Id = r.Id; Name = r.Name; Age = r.Age } : Customer

result |> toCustomer
results |> Seq.map toCustomer

As you can imagine, the more queries I have, the more I need to copy and paste that code, and the more columns I return, the noisier it gets.

Another option would be to be able to provide my own record, something like this:

SqlCommandProvider<"SELECT Id, Name, Age FROM Customers WHERE id = @Id", cn, typeofCustomer>

I apologise if there is already a way to do this, I couldn't find it.

Thanks a lot!

**Comment by DunetsNM** [comment]
F# 4.0 feature "type provider methods with static parameters" is implemented now. Should issue be reopened?
This should be a popular demand, it is pretty common to have multiple queries that return same table structure (and then mapped to the same domain type).

**Comment by NickDarvey** [comment]
@DunetsNM or perhaps @dmitry-a-morozov, is there a better way of dealing with this these days? This is my first experience with F# and type providers and I feel I must be missing something.

**Comment by DunetsNM** [comment]
@NickDarvey I still do mapping based on static member constraints like suggested above. Not ideal but better than nothing.
